#!/usr/bin/env python3
"""Generate Sources/Mojito/GifPicker/EmbeddedGiphyKey.swift from .env.

Reads `GIPHY_API_KEY` from (in priority order):
  1. The `GIPHY_API_KEY` environment variable.
  2. A `.env` file at the repo root (KEY=VALUE, optional surrounding quotes,
     optional `export ` prefix — same shape `scripts/release.sh` sources).

If no key is found, writes a file with empty bytes so the project still
compiles on a fresh clone with no `.env`. The runtime fallback chain in
`GifSearcher.apiKey` lets users still paste a key into UserDefaults
(`mojito.giphyApiKey`) or set `GIPHY_API_KEY` in the launch environment.

The bytes written to the .swift file are XOR-masked against a rolling key
starting at `0x5C` — trivially reversible but defeats `strings(1)` and a
casual repo skim of the shipped binary. Same shape as `EggStrings.swift`.
This is obfuscation, not encryption: any client-side secret can be
recovered by a determined reverser. The aim is just to keep it out of
trivial reach so the public-shared key isn't lifted by anyone scrolling
through the binary.

Wired in via `project.yml`:
  - `options.preGenCommand`  → bootstraps the file before xcodegen scans
    `Sources/Mojito` on a fresh clone.
  - `targets.Mojito.preBuildScripts` → regenerates on every build so
    `.env` edits flow through without an explicit `xcodegen generate`.

The generated file is gitignored. To avoid spurious Xcode rebuilds, the
script no-ops when the existing file already matches.
"""

import os
import sys
from pathlib import Path
from typing import Optional

XOR_BASE = 0x5C
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "Sources" / "Mojito" / "GifPicker" / "EmbeddedGiphyKey.swift"
ENV_PATH = REPO_ROOT / ".env"


def read_dotenv_value(path: Path, key: str) -> Optional[str]:
    if not path.exists():
        return None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        if k.strip() != key:
            continue
        v = v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
            v = v[1:-1]
        return v
    return None


def encode(text: str) -> "list[int]":
    raw = text.encode("utf-8")
    return [b ^ ((XOR_BASE + i) & 0xFF) for i, b in enumerate(raw)]


def render(key: str) -> str:
    bytes_ = encode(key)
    bytes_str = ", ".join(f"0x{b:02x}" for b in bytes_)
    return (
        "import Foundation\n"
        "\n"
        "/// Giphy API key baked in at build time from `GIPHY_API_KEY` (env\n"
        "/// var or `.env` at repo root). Bytes below are XOR-masked against a\n"
        f"/// rolling key starting at `0x{XOR_BASE:02X}` so `strings <binary>` and a\n"
        "/// casual binary skim won't surface the plaintext. Trivially\n"
        "/// reversible — this is obfuscation, not encryption; any client-side\n"
        "/// secret can be lifted by a determined attacker. Aim is just to keep\n"
        "/// the embedded key out of trivial reach.\n"
        "///\n"
        "/// Regenerated by `scripts/build_giphy_key.py`; see that script's\n"
        "/// header for the wiring. This file is gitignored.\n"
        "enum EmbeddedGiphyKey {\n"
        f"    static let value: String = decode([{bytes_str}])\n"
        "\n"
        "    private static func decode(_ bytes: [UInt8]) -> String {\n"
        "        var out = [UInt8]()\n"
        "        out.reserveCapacity(bytes.count)\n"
        "        for (i, b) in bytes.enumerated() {\n"
        f"            out.append(b ^ UInt8((0x{XOR_BASE:02X} &+ i) & 0xFF))\n"
        "        }\n"
        "        return String(decoding: out, as: UTF8.self)\n"
        "    }\n"
        "}\n"
    )


def main() -> None:
    key = os.environ.get("GIPHY_API_KEY") or read_dotenv_value(ENV_PATH, "GIPHY_API_KEY") or ""
    content = render(key)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists() and OUT_PATH.read_text() == content:
        return

    OUT_PATH.write_text(content)
    rel = OUT_PATH.relative_to(REPO_ROOT)
    if key:
        print(f"[build_giphy_key] wrote {rel} ({len(key)}-char key)", file=sys.stderr)
    else:
        print(
            f"[build_giphy_key] wrote {rel} with empty key — GIF search will "
            "show 'API key required' until GIPHY_API_KEY is set in .env",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
