#!/usr/bin/env python3
"""Generate emoji-codes.js — a hexcode -> primary-shortcode map for the stats page.

The stats worker returns only opaque hexcodes (no identifiers, counts only), so
the Top-emoji list has to turn a hexcode like `1f64f` into a human-readable
`:pray:` on the client. This bakes that lookup table from Mojito's canonical
emoji database (the same `h`/`s` fields the app indexes), keyed by the exact
hexcode the app records into telemetry.

Rare to run — only when the bundled emoji DB bumps. Output is committed.

Usage:
    python3 scripts/build-emoji-codes.py [path/to/emoji.json]

Default source is the sibling app checkout: ../mojito/Resources/Emoji/emoji.json
"""
import json
import sys
from pathlib import Path

DEFAULT_SRC = Path(__file__).resolve().parent.parent.parent / "mojito" / "Resources" / "Emoji" / "emoji.json"
OUT = Path(__file__).resolve().parent.parent / "emoji-codes.js"


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.exists():
        print(f"emoji.json not found at {src}\n"
              f"Pass the path explicitly: python3 scripts/build-emoji-codes.py <path>",
              file=sys.stderr)
        return 1

    db = json.loads(src.read_text())
    # h -> primary shortcode (s[0]). Key lowercased to match `hexcode.toLowerCase()`
    # in stats-live.js. Sorted for stable diffs.
    table = {}
    for e in db:
        codes = e.get("s") or []
        if codes:
            table[e["h"].lower()] = codes[0]
    table = dict(sorted(table.items()))

    blob = json.dumps(table, separators=(",", ":"), ensure_ascii=False)
    OUT.write_text(
        "/* Generated by scripts/build-emoji-codes.py — do not hand-edit.\n"
        "   Maps the telemetry hexcode the worker returns to a primary :shortcode:\n"
        "   for the Top-emoji list (stats-live.js). Regenerate when the emoji DB\n"
        "   bumps: python3 scripts/build-emoji-codes.py */\n"
        f"window.MojitoEmojiCodes={blob};\n"
    )
    print(f"wrote {OUT.name}: {len(table)} entries, {len(blob)} bytes from {src}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
