#!/usr/bin/env python3
"""Generate the embedded GIF provider API key files from .env.

Writes one file per provider:
  - Sources/Mojito/GifPicker/EmbeddedGiphyKey.swift  ← `GIPHY_API_KEY`
  - Sources/Mojito/GifPicker/EmbeddedKlipyKey.swift  ← `KLIPY_API_KEY`

Reads each key from (in priority order):
  1. The environment variable of the same name.
  2. A `.env` file at the repo root (KEY=VALUE, optional surrounding quotes,
     optional `export ` prefix — same shape `scripts/release.sh` sources).

If a key is missing, writes a file with empty bytes so the project still
compiles on a fresh clone with no `.env`. The runtime fallback chain in
`GifProvider.apiKey` lets users still paste a key into UserDefaults
(`mojito.giphyApiKey` / `mojito.klipyApiKey`) or set the env var at launch.

The bytes written to the .swift file are XOR-masked against a rolling key
starting at `0x5C` — trivially reversible but defeats `strings(1)` and a
casual repo skim of the shipped binary. Same shape as `EggStrings.swift`.
This is obfuscation, not encryption: any client-side secret can be
recovered by a determined reverser. The aim is just to keep it out of
trivial reach so the public-shared key isn't lifted by anyone scrolling
through the binary.

Wired in via `project.yml`:
  - `options.preGenCommand`  → bootstraps the file before xcodegen scans
    `Sources/Mojito` on a fresh clone.
  - `targets.Mojito.preBuildScripts` → regenerates on every build so
    `.env` edits flow through without an explicit `xcodegen generate`.

The generated files are gitignored. To avoid spurious Xcode rebuilds, the
script leaves a file untouched when its content already matches.
"""

import os
import sys
from pathlib import Path
from typing import Optional

XOR_BASE = 0x5C
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "Sources" / "Mojito" / "GifPicker"
# (env var, Swift enum name, provider name used in the doc comment)
PROVIDERS = [
    ("GIPHY_API_KEY", "EmbeddedGiphyKey", "Giphy"),
    ("KLIPY_API_KEY", "EmbeddedKlipyKey", "KLIPY"),
]
ENV_PATH = REPO_ROOT / ".env"


def read_dotenv_value(path: Path, key: str) -> Optional[str]:
    if not path.exists():
        return None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        if k.strip() != key:
            continue
        v = v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
            v = v[1:-1]
        return v
    return None


def encode(text: str) -> "list[int]":
    raw = text.encode("utf-8")
    return [b ^ ((XOR_BASE + i) & 0xFF) for i, b in enumerate(raw)]


def render(key: str, env_name: str, enum_name: str, label: str) -> str:
    bytes_ = encode(key)
    bytes_str = ", ".join(f"0x{b:02x}" for b in bytes_)
    return (
        "import Foundation\n"
        "\n"
        f"/// {label} API key baked in at build time from `{env_name}` (env\n"
        "/// var or `.env` at repo root). Bytes below are XOR-masked against a\n"
        f"/// rolling key starting at `0x{XOR_BASE:02X}` so `strings <binary>` and a\n"
        "/// casual binary skim won't surface the plaintext. Trivially\n"
        "/// reversible — this is obfuscation, not encryption; any client-side\n"
        "/// secret can be lifted by a determined attacker. Aim is just to keep\n"
        "/// the embedded key out of trivial reach.\n"
        "///\n"
        "/// Regenerated by `scripts/build_giphy_key.py`; see that script's\n"
        "/// header for the wiring. This file is gitignored.\n"
        f"enum {enum_name} {{\n"
        f"    static let value: String = decode([{bytes_str}])\n"
        "\n"
        "    private static func decode(_ bytes: [UInt8]) -> String {\n"
        "        var out = [UInt8]()\n"
        "        out.reserveCapacity(bytes.count)\n"
        "        for (i, b) in bytes.enumerated() {\n"
        f"            out.append(b ^ UInt8((0x{XOR_BASE:02X} &+ i) & 0xFF))\n"
        "        }\n"
        "        return String(decoding: out, as: UTF8.self)\n"
        "    }\n"
        "}\n"
    )


def write_key_file(env_name: str, enum_name: str, label: str) -> None:
    key = os.environ.get(env_name) or read_dotenv_value(ENV_PATH, env_name) or ""
    content = render(key, env_name, enum_name, label)
    out_path = OUT_DIR / f"{enum_name}.swift"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists() and out_path.read_text() == content:
        return

    out_path.write_text(content)
    rel = out_path.relative_to(REPO_ROOT)
    if key:
        print(f"[build_giphy_key] wrote {rel} ({len(key)}-char key)", file=sys.stderr)
    else:
        print(
            f"[build_giphy_key] wrote {rel} with empty key — {label} GIF search "
            f"will show 'API key required' until {env_name} is set in .env",
            file=sys.stderr,
        )


def main() -> None:
    for env_name, enum_name, label in PROVIDERS:
        write_key_file(env_name, enum_name, label)


if __name__ == "__main__":
    main()
