#!/usr/bin/env python3
"""Populate Resources/Localizable.xcstrings with LLM-drafted translations.

Translations live in the TRANSLATIONS dict below — they were drafted by an
LLM and need a native-speaker pass before public release. Re-run this
script after editing any value to apply changes to the catalog.

The script is idempotent and additive: it sets `state` to `translated`
for any (key, locale) pair present here. Anything you've manually edited
in the catalog with `state: "needs_review"` or `state: "reviewed"` will
NOT be overwritten unless you change it back to `new`.

Usage:
    python3 scripts/translate-localizable.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "Resources" / "Localizable.xcstrings"

# Locales in column order. en is the source — translations elsewhere.
LOCALES = [
    "en-GB", "de", "es", "es-419", "fr", "it", "pt-BR",
    "ja", "zh-Hans", "zh-Hant", "ko",
    "hi", "ru", "pl", "nl",
    "ar", "fa", "he",
]

# Drafted translations. Tone: informal-friendly, matches the English
# source. Placeholders (%@, %lld, %1$@, %1$lld), Markdown, and backticked
# code samples are preserved verbatim.
TRANSLATIONS: dict[str, dict[str, str]] = {
    "%@ couldn't reach the update server.": {
        "en-GB": "%@ couldn't reach the update server.",
        "de": "%@ konnte den Update-Server nicht erreichen.",
        "es": "%@ no pudo conectar con el servidor de actualizaciones.",
        "es-419": "%@ no pudo conectar con el servidor de actualizaciones.",
        "fr": "%@ n'a pas pu joindre le serveur de mises à jour.",
        "it": "%@ non è riuscito a raggiungere il server degli aggiornamenti.",
        "pt-BR": "%@ não conseguiu acessar o servidor de atualizações.",
        "ja": "%@ はアップデートサーバーに接続できませんでした。",
        "zh-Hans": "%@ 无法连接到更新服务器。",
        "zh-Hant": "%@ 無法連線到更新伺服器。",
        "ko": "%@이(가) 업데이트 서버에 연결할 수 없습니다.",
        "hi": "%@ अपडेट सर्वर तक नहीं पहुँच सका।",
        "ru": "%@ не удалось связаться с сервером обновлений.",
        "pl": "%@ nie mógł połączyć się z serwerem aktualizacji.",
        "nl": "%@ kon de update-server niet bereiken.",
        "ar": "تعذّر على %@ الوصول إلى خادم التحديثات.",
        "fa": "‏%@ نتوانست به سرور به‌روزرسانی متصل شود.",
        "he": "‏%@ לא הצליח להתחבר לשרת העדכונים.",
    },
    "%@ is built to respect your privacy. Here's how.": {
        "en-GB": "%@ is built to respect your privacy. Here's how.",
        "de": "%@ ist auf den Schutz deiner Privatsphäre ausgelegt. So funktioniert's.",
        "es": "%@ está hecho para respetar tu privacidad. Así lo hace.",
        "es-419": "%@ está hecho para respetar tu privacidad. Así lo hace.",
        "fr": "%@ est conçu pour respecter votre vie privée. Voici comment.",
        "it": "%@ è progettato per rispettare la tua privacy. Ecco come.",
        "pt-BR": "%@ foi feito para respeitar sua privacidade. Veja como.",
        "ja": "%@ はあなたのプライバシーを尊重するように作られています。その仕組みをご紹介します。",
        "zh-Hans": "%@ 在设计时充分尊重你的隐私。以下是具体方式。",
        "zh-Hant": "%@ 設計時就以保護你的隱私為前提。以下是做法。",
        "ko": "%@은(는) 사용자의 개인정보를 존중하도록 만들어졌습니다. 그 방법은 다음과 같습니다.",
        "hi": "%@ आपकी निजता का सम्मान करने के लिए बनाया गया है। यह इस तरह काम करता है।",
        "ru": "%@ создан с уважением к вашей конфиденциальности. Вот как именно.",
        "pl": "%@ został zaprojektowany z myślą o twojej prywatności. Oto jak.",
        "nl": "%@ is gebouwd met respect voor je privacy. Zo werkt het.",
        "ar": "صُمِّم %@ لاحترام خصوصيتك. إليك كيف.",
        "fa": "‏%@ برای احترام به حریم خصوصی شما ساخته شده است. به این صورت:",
        "he": "‏%@ נבנה תוך כיבוד הפרטיות שלך. כך זה עובד.",
    },
    "%@ is forever free, but your support helps fund future projects. Thank you!": {
        "en-GB": "%@ is forever free, but your support helps fund future projects. Thank you!",
        "de": "%@ bleibt für immer kostenlos – deine Unterstützung hilft aber, zukünftige Projekte zu finanzieren. Danke!",
        "es": "%@ es siempre gratis, pero tu apoyo ayuda a financiar futuros proyectos. ¡Gracias!",
        "es-419": "%@ es siempre gratis, pero tu apoyo ayuda a financiar futuros proyectos. ¡Gracias!",
        "fr": "%@ est gratuit pour toujours, mais votre soutien aide à financer les projets futurs. Merci !",
        "it": "%@ è gratis per sempre, ma il tuo supporto aiuta a finanziare progetti futuri. Grazie!",
        "pt-BR": "%@ é grátis para sempre, mas seu apoio ajuda a financiar projetos futuros. Obrigado!",
        "ja": "%@ はずっと無料ですが、あなたのご支援は今後のプロジェクトの資金になります。ありがとうございます！",
        "zh-Hans": "%@ 永久免费,但你的支持能帮助资助未来的项目。谢谢!",
        "zh-Hant": "%@ 永遠免費,但你的支持能幫助贊助未來的專案。謝謝!",
        "ko": "%@은(는) 영원히 무료지만, 후원해 주시면 앞으로의 프로젝트에 큰 힘이 됩니다. 감사합니다!",
        "hi": "%@ हमेशा मुफ़्त है, लेकिन आपका सहयोग भविष्य की परियोजनाओं को बनाने में मदद करता है। धन्यवाद!",
        "ru": "%@ навсегда бесплатен, но ваша поддержка помогает финансировать будущие проекты. Спасибо!",
        "pl": "%@ jest darmowy na zawsze, ale twoje wsparcie pomaga finansować przyszłe projekty. Dziękuję!",
        "nl": "%@ is voor altijd gratis, maar je steun helpt om toekomstige projecten te financieren. Bedankt!",
        "ar": "‏%@ مجاني إلى الأبد، لكن دعمك يساعد على تمويل المشاريع المستقبلية. شكراً لك!",
        "fa": "‏%@ همیشه رایگان است، اما حمایت شما به تأمین مالی پروژه‌های آینده کمک می‌کند. ممنون!",
        "he": "‏%@ חינמי לתמיד, אבל התמיכה שלך עוזרת לממן פרויקטים עתידיים. תודה!",
    },
    "%@ is off": {
        "en-GB": "%@ is off",
        "de": "%@ ist aus",
        "es": "%@ está desactivado",
        "es-419": "%@ está desactivado",
        "fr": "%@ est désactivé",
        "it": "%@ è disattivato",
        "pt-BR": "%@ está desativado",
        "ja": "%@ はオフです",
        "zh-Hans": "%@ 已关闭",
        "zh-Hant": "%@ 已關閉",
        "ko": "%@이(가) 꺼져 있음",
        "hi": "%@ बंद है",
        "ru": "%@ выключен",
        "pl": "%@ jest wyłączony",
        "nl": "%@ is uit",
        "ar": "‏%@ متوقّف",
        "fa": "‏%@ خاموش است",
        "he": "‏%@ כבוי",
    },
    "%@ is on": {
        "en-GB": "%@ is on",
        "de": "%@ ist an",
        "es": "%@ está activado",
        "es-419": "%@ está activado",
        "fr": "%@ est activé",
        "it": "%@ è attivo",
        "pt-BR": "%@ está ativado",
        "ja": "%@ はオンです",
        "zh-Hans": "%@ 已开启",
        "zh-Hant": "%@ 已開啟",
        "ko": "%@이(가) 켜져 있음",
        "hi": "%@ चालू है",
        "ru": "%@ включён",
        "pl": "%@ jest włączony",
        "nl": "%@ is aan",
        "ar": "‏%@ مُشغَّل",
        "fa": "‏%@ روشن است",
        "he": "‏%@ פועל",
    },
    "%@ is paused": {
        "en-GB": "%@ is paused",
        "de": "%@ ist pausiert",
        "es": "%@ está en pausa",
        "es-419": "%@ está en pausa",
        "fr": "%@ est en pause",
        "it": "%@ è in pausa",
        "pt-BR": "%@ está pausado",
        "ja": "%@ は一時停止中です",
        "zh-Hans": "%@ 已暂停",
        "zh-Hant": "%@ 已暫停",
        "ko": "%@이(가) 일시 중지됨",
        "hi": "%@ रोका गया है",
        "ru": "%@ приостановлен",
        "pl": "%@ jest wstrzymany",
        "nl": "%@ is gepauzeerd",
        "ar": "‏%@ موقوف مؤقّتاً",
        "fa": "‏%@ متوقّف شده است",
        "he": "‏%@ מושהה",
    },
    "%@ is running 🏃‍♂️": {
        "en-GB": "%@ is running 🏃‍♂️",
        "de": "%@ läuft 🏃‍♂️",
        "es": "%@ está en marcha 🏃‍♂️",
        "es-419": "%@ está en marcha 🏃‍♂️",
        "fr": "%@ tourne 🏃‍♂️",
        "it": "%@ è in esecuzione 🏃‍♂️",
        "pt-BR": "%@ está rodando 🏃‍♂️",
        "ja": "%@ は動作中です 🏃‍♂️",
        "zh-Hans": "%@ 正在运行 🏃‍♂️",
        "zh-Hant": "%@ 正在執行 🏃‍♂️",
        "ko": "%@ 실행 중 🏃‍♂️",
        "hi": "%@ चल रहा है 🏃‍♂️",
        "ru": "%@ работает 🏃‍♂️",
        "pl": "%@ działa 🏃‍♂️",
        "nl": "%@ draait 🏃‍♂️",
        "ar": "‏%@ يعمل 🏃‍♂️",
        "fa": "‏%@ در حال اجراست 🏃‍♂️",
        "he": "‏%@ פועל 🏃‍♂️",
    },
    "%@ lives in your menu bar. Try typing `:tada:` in any text field.": {
        "en-GB": "%@ lives in your menu bar. Try typing `:tada:` in any text field.",
        "de": "%@ wohnt in deiner Menüleiste. Tippe `:tada:` in ein beliebiges Textfeld.",
        "es": "%@ vive en tu barra de menús. Prueba a escribir `:tada:` en cualquier campo de texto.",
        "es-419": "%@ vive en tu barra de menús. Probá escribir `:tada:` en cualquier campo de texto.",
        "fr": "%@ vit dans votre barre de menus. Essayez de taper `:tada:` dans n'importe quel champ.",
        "it": "%@ vive nella tua barra dei menu. Prova a digitare `:tada:` in un campo di testo.",
        "pt-BR": "%@ mora na sua barra de menus. Experimente digitar `:tada:` em qualquer campo de texto.",
        "ja": "%@ はメニューバーに常駐します。任意のテキストフィールドで `:tada:` と入力してみてください。",
        "zh-Hans": "%@ 就在你的菜单栏里。在任何文本框中尝试输入 `:tada:`。",
        "zh-Hant": "%@ 就在你的選單列裡。在任何文字輸入框試試輸入 `:tada:`。",
        "ko": "%@은(는) 메뉴 막대에서 작동합니다. 아무 텍스트 필드에 `:tada:` 를 입력해 보세요.",
        "hi": "%@ आपके मेन्यू बार में रहता है। किसी भी टेक्स्ट फ़ील्ड में `:tada:` टाइप करके देखें।",
        "ru": "%@ живёт в строке меню. Попробуйте ввести `:tada:` в любом текстовом поле.",
        "pl": "%@ mieszka na pasku menu. Wpisz `:tada:` w dowolne pole tekstowe.",
        "nl": "%@ woont in je menubalk. Probeer `:tada:` te typen in een tekstveld.",
        "ar": "يعيش %@ في شريط القوائم لديك. جرّب كتابة `:tada:` في أي حقل نصي.",
        "fa": "‏%@ در نوار منوی شما زندگی می‌کند. در هر فیلد متنی `:tada:` را امتحان کنید.",
        "he": "‏%@ גר בשורת התפריטים שלך. נסה להקליד `:tada:` בכל שדה טקסט.",
    },
    "%@ needs permission": {
        "en-GB": "%@ needs permission",
        "de": "%@ benötigt eine Berechtigung",
        "es": "%@ necesita permisos",
        "es-419": "%@ necesita permisos",
        "fr": "%@ a besoin d'une autorisation",
        "it": "%@ necessita di permessi",
        "pt-BR": "%@ precisa de permissão",
        "ja": "%@ には権限が必要です",
        "zh-Hans": "%@ 需要权限",
        "zh-Hant": "%@ 需要權限",
        "ko": "%@에 권한이 필요합니다",
        "hi": "%@ को अनुमति चाहिए",
        "ru": "%@ требуются разрешения",
        "pl": "%@ wymaga uprawnień",
        "nl": "%@ heeft toestemming nodig",
        "ar": "يحتاج %@ إلى إذن",
        "fa": "‏%@ به اجازه نیاز دارد",
        "he": "‏%@ זקוק להרשאה",
    },
    "%@ needs permission to work with your keyboard.": {
        "en-GB": "%@ needs permission to work with your keyboard.",
        "de": "%@ benötigt eine Berechtigung, um mit deiner Tastatur zu arbeiten.",
        "es": "%@ necesita permisos para funcionar con tu teclado.",
        "es-419": "%@ necesita permisos para funcionar con tu teclado.",
        "fr": "%@ a besoin d'une autorisation pour fonctionner avec votre clavier.",
        "it": "%@ necessita di permessi per funzionare con la tua tastiera.",
        "pt-BR": "%@ precisa de permissão para funcionar com seu teclado.",
        "ja": "%@ がキーボードと連携するには権限が必要です。",
        "zh-Hans": "%@ 需要权限才能与键盘配合工作。",
        "zh-Hant": "%@ 需要權限才能與鍵盤搭配運作。",
        "ko": "%@이(가) 키보드와 함께 작동하려면 권한이 필요합니다.",
        "hi": "आपके कीबोर्ड के साथ काम करने के लिए %@ को अनुमति चाहिए।",
        "ru": "%@ требуются разрешения для работы с клавиатурой.",
        "pl": "%@ wymaga uprawnień do pracy z twoją klawiaturą.",
        "nl": "%@ heeft toestemming nodig om met je toetsenbord te werken.",
        "ar": "يحتاج %@ إلى إذن للعمل مع لوحة المفاتيح.",
        "fa": "‏%@ برای کار با صفحه‌کلید شما به اجازه نیاز دارد.",
        "he": "‏%@ זקוק להרשאה כדי לפעול עם המקלדת שלך.",
    },
    "%lld of %lld": {
        # English source already specifies "%1$lld of %2$lld" — preserve.
        "en-GB": "%1$lld of %2$lld",
        "de": "%1$lld von %2$lld",
        "es": "%1$lld de %2$lld",
        "es-419": "%1$lld de %2$lld",
        "fr": "%1$lld sur %2$lld",
        "it": "%1$lld su %2$lld",
        "pt-BR": "%1$lld de %2$lld",
        "ja": "%2$lld 中 %1$lld",
        "zh-Hans": "%2$lld 中的 %1$lld",
        "zh-Hant": "%2$lld 中的 %1$lld",
        "ko": "%2$lld개 중 %1$lld개",
        "hi": "%2$lld में से %1$lld",
        "ru": "%1$lld из %2$lld",
        "pl": "%1$lld z %2$lld",
        "nl": "%1$lld van %2$lld",
        "ar": "%1$lld من %2$lld",
        "fa": "%1$lld از %2$lld",
        "he": "%1$lld מתוך %2$lld",
    },
    "???": {
        # Three-unknowns placeholder per the source-side comment. All
        # locales keep the literal character sequence so it reads as a
        # mystery regardless of language.
        "en-GB": "???",
        "de": "???",
        "es": "???",
        "es-419": "???",
        "fr": "???",
        "it": "???",
        "pt-BR": "???",
        "ja": "???",
        "zh-Hans": "???",
        "zh-Hant": "???",
        "ko": "???",
        "hi": "???",
        "ru": "???",
        "pl": "???",
        "nl": "???",
        "ar": "؟؟؟",
        "fa": "؟؟؟",
        "he": "???",
    },
    "About": {
        "en-GB": "About",
        "de": "Über",
        "es": "Acerca de",
        "es-419": "Acerca de",
        "fr": "À propos",
        "it": "Informazioni",
        "pt-BR": "Sobre",
        "ja": "情報",
        "zh-Hans": "关于",
        "zh-Hant": "關於",
        "ko": "정보",
        "hi": "बारे में",
        "ru": "О программе",
        "pl": "Informacje",
        "nl": "Over",
        "ar": "حول",
        "fa": "درباره",
        "he": "אודות",
    },
    "Accessibility": {
        "en-GB": "Accessibility",
        "de": "Bedienungshilfen",
        "es": "Accesibilidad",
        "es-419": "Accesibilidad",
        "fr": "Accessibilité",
        "it": "Accessibilità",
        "pt-BR": "Acessibilidade",
        "ja": "アクセシビリティ",
        "zh-Hans": "辅助功能",
        "zh-Hant": "輔助使用",
        "ko": "손쉬운 사용",
        "hi": "ऐक्सेसिबिलिटी",
        "ru": "Универсальный доступ",
        "pl": "Dostępność",
        "nl": "Toegankelijkheid",
        "ar": "إمكانية الوصول",
        "fa": "دسترس‌پذیری",
        "he": "נגישות",
    },
    "Acknowledgements": {
        "en-GB": "Acknowledgements",
        "de": "Danksagungen",
        "es": "Agradecimientos",
        "es-419": "Agradecimientos",
        "fr": "Remerciements",
        "it": "Ringraziamenti",
        "pt-BR": "Agradecimentos",
        "ja": "謝辞",
        "zh-Hans": "鸣谢",
        "zh-Hant": "致謝",
        "ko": "감사의 말",
        "hi": "आभार",
        "ru": "Благодарности",
        "pl": "Podziękowania",
        "nl": "Met dank aan",
        "ar": "شُكر وتقدير",
        "fa": "تقدیر و تشکر",
        "he": "תודות",
    },
    "Add": {
        "en-GB": "Add",
        "de": "Hinzufügen",
        "es": "Añadir",
        "es-419": "Agregar",
        "fr": "Ajouter",
        "it": "Aggiungi",
        "pt-BR": "Adicionar",
        "ja": "追加",
        "zh-Hans": "添加",
        "zh-Hant": "加入",
        "ko": "추가",
        "hi": "जोड़ें",
        "ru": "Добавить",
        "pl": "Dodaj",
        "nl": "Voeg toe",
        "ar": "إضافة",
        "fa": "افزودن",
        "he": "הוסף",
    },
    "Add website": {
        "en-GB": "Add website",
        "de": "Website hinzufügen",
        "es": "Añadir sitio web",
        "es-419": "Agregar sitio web",
        "fr": "Ajouter un site web",
        "it": "Aggiungi sito web",
        "pt-BR": "Adicionar site",
        "ja": "ウェブサイトを追加",
        "zh-Hans": "添加网站",
        "zh-Hant": "加入網站",
        "ko": "웹사이트 추가",
        "hi": "वेबसाइट जोड़ें",
        "ru": "Добавить сайт",
        "pl": "Dodaj witrynę",
        "nl": "Website toevoegen",
        "ar": "إضافة موقع",
        "fa": "افزودن وب‌سایت",
        "he": "הוסף אתר",
    },
    "All the code is on GitHub. Read it, build it, fork it.": {
        "en-GB": "All the code is on GitHub. Read it, build it, fork it.",
        "de": "Der gesamte Code liegt auf GitHub. Lies ihn, baue ihn, forke ihn.",
        "es": "Todo el código está en GitHub. Léelo, compílalo, bifúrcalo.",
        "es-419": "Todo el código está en GitHub. Leelo, compilalo, bifurcalo.",
        "fr": "Tout le code est sur GitHub. Lisez-le, compilez-le, forkez-le.",
        "it": "Tutto il codice è su GitHub. Leggilo, compilalo, fai un fork.",
        "pt-BR": "Todo o código está no GitHub. Leia, compile, faça um fork.",
        "ja": "すべてのコードは GitHub にあります。読んで、ビルドして、フォークしてください。",
        "zh-Hans": "所有代码都在 GitHub 上。读它、构建它、fork 它。",
        "zh-Hant": "所有原始碼都在 GitHub 上。閱讀、建置、fork 隨你便。",
        "ko": "모든 코드는 GitHub에 있습니다. 읽고, 빌드하고, 포크하세요.",
        "hi": "सारा कोड GitHub पर है। पढ़ें, बिल्ड करें, फ़ोर्क करें।",
        "ru": "Весь код — на GitHub. Читайте, собирайте, форкайте.",
        "pl": "Cały kod jest na GitHubie. Czytaj, buduj, forkuj.",
        "nl": "Alle code staat op GitHub. Lees het, bouw het, fork het.",
        "ar": "كل الكود موجود على GitHub. اقرأه، اِبنه، فُرّعه.",
        "fa": "همهٔ کد در GitHub است. بخوانید، بسازید، فورک کنید.",
        "he": "כל הקוד נמצא ב-GitHub. קרא, בנה, פצל לפורק.",
    },
    "Allow": {
        "en-GB": "Allow",
        "de": "Erlauben",
        "es": "Permitir",
        "es-419": "Permitir",
        "fr": "Autoriser",
        "it": "Consenti",
        "pt-BR": "Permitir",
        "ja": "許可",
        "zh-Hans": "允许",
        "zh-Hant": "允許",
        "ko": "허용",
        "hi": "अनुमति दें",
        "ru": "Разрешить",
        "pl": "Zezwól",
        "nl": "Sta toe",
        "ar": "السماح",
        "fa": "اجازه دادن",
        "he": "אפשר",
    },
    "Anchors the picker next to your text cursor.": {
        "en-GB": "Anchors the picker next to your text cursor.",
        "de": "Verankert den Picker neben deinem Textcursor.",
        "es": "Ancla el selector junto al cursor de texto.",
        "es-419": "Ancla el selector junto al cursor de texto.",
        "fr": "Ancre le sélecteur à côté de votre curseur de texte.",
        "it": "Àncora il selettore accanto al cursore di testo.",
        "pt-BR": "Ancora o seletor ao lado do cursor de texto.",
        "ja": "ピッカーをテキストカーソルの隣に固定します。",
        "zh-Hans": "将选取器锚定在文本光标旁。",
        "zh-Hant": "將選取器固定在文字游標旁邊。",
        "ko": "선택기를 텍스트 커서 옆에 고정합니다.",
        "hi": "पिकर को आपके टेक्स्ट कर्सर के बगल में जोड़ता है।",
        "ru": "Закрепляет окно подбора рядом с текстовым курсором.",
        "pl": "Umieszcza okno wyboru obok kursora tekstu.",
        "nl": "Verankert de kiezer naast je tekstcursor.",
        "ar": "يثبّت أداة الاختيار بجوار مؤشر النص.",
        "fa": "انتخابگر را کنار مکان‌نمای متن قرار می‌دهد.",
        "he": "מעגן את הבורר ליד סמן הטקסט.",
    },
    "Autocomplete `:emoji:` everywhere.": {
        "en-GB": "Autocomplete `:emoji:` everywhere.",
        "de": "`:emoji:` überall automatisch vervollständigen.",
        "es": "Autocompleta `:emoji:` en todas partes.",
        "es-419": "Autocompleta `:emoji:` en todas partes.",
        "fr": "Autocomplétez `:emoji:` partout.",
        "it": "Completamento automatico di `:emoji:` ovunque.",
        "pt-BR": "Autocompletar `:emoji:` em qualquer lugar.",
        "ja": "どこでも `:emoji:` を自動補完。",
        "zh-Hans": "随处自动补全 `:emoji:`。",
        "zh-Hant": "到處都能自動完成 `:emoji:`。",
        "ko": "어디서나 `:emoji:` 자동 완성.",
        "hi": "हर जगह `:emoji:` ऑटोकम्प्लीट करें।",
        "ru": "Автодополнение `:emoji:` где угодно.",
        "pl": "Autouzupełnianie `:emoji:` wszędzie.",
        "nl": "Autocomplete `:emoji:` overal.",
        "ar": "الإكمال التلقائي لـ `:emoji:` في كل مكان.",
        "fa": "تکمیل خودکار `:emoji:` همه‌جا.",
        "he": "השלמה אוטומטית של `:emoji:` בכל מקום.",
    },
    "Automatic updates": {
        "en-GB": "Automatic updates",
        "de": "Automatische Updates",
        "es": "Actualizaciones automáticas",
        "es-419": "Actualizaciones automáticas",
        "fr": "Mises à jour automatiques",
        "it": "Aggiornamenti automatici",
        "pt-BR": "Atualizações automáticas",
        "ja": "自動アップデート",
        "zh-Hans": "自动更新",
        "zh-Hant": "自動更新",
        "ko": "자동 업데이트",
        "hi": "स्वचालित अपडेट",
        "ru": "Автоматические обновления",
        "pl": "Automatyczne aktualizacje",
        "nl": "Automatische updates",
        "ar": "التحديثات التلقائية",
        "fa": "به‌روزرسانی خودکار",
        "he": "עדכונים אוטומטיים",
    },
    "Back": {
        "en-GB": "Back",
        "de": "Zurück",
        "es": "Atrás",
        "es-419": "Atrás",
        "fr": "Retour",
        "it": "Indietro",
        "pt-BR": "Voltar",
        "ja": "戻る",
        "zh-Hans": "返回",
        "zh-Hant": "返回",
        "ko": "뒤로",
        "hi": "पीछे",
        "ru": "Назад",
        "pl": "Wstecz",
        "nl": "Terug",
        "ar": "رجوع",
        "fa": "بازگشت",
        "he": "חזרה",
    },
    "Cancel": {
        "en-GB": "Cancel",
        "de": "Abbrechen",
        "es": "Cancelar",
        "es-419": "Cancelar",
        "fr": "Annuler",
        "it": "Annulla",
        "pt-BR": "Cancelar",
        "ja": "キャンセル",
        "zh-Hans": "取消",
        "zh-Hant": "取消",
        "ko": "취소",
        "hi": "रद्द करें",
        "ru": "Отмена",
        "pl": "Anuluj",
        "nl": "Annuleer",
        "ar": "إلغاء",
        "fa": "لغو",
        "he": "ביטול",
    },
    "Check for Updates…": {
        "en-GB": "Check for Updates…",
        "de": "Auf Updates prüfen…",
        "es": "Buscar actualizaciones…",
        "es-419": "Buscar actualizaciones…",
        "fr": "Rechercher les mises à jour…",
        "it": "Cerca aggiornamenti…",
        "pt-BR": "Verificar atualizações…",
        "ja": "アップデートを確認…",
        "zh-Hans": "检查更新…",
        "zh-Hant": "檢查更新…",
        "ko": "업데이트 확인…",
        "hi": "अपडेट देखें…",
        "ru": "Проверить обновления…",
        "pl": "Sprawdź aktualizacje…",
        "nl": "Zoek naar updates…",
        "ar": "التحقّق من التحديثات…",
        "fa": "بررسی به‌روزرسانی‌ها…",
        "he": "בדוק עדכונים…",
    },
    "Check now": {
        "en-GB": "Check now",
        "de": "Jetzt prüfen",
        "es": "Buscar ahora",
        "es-419": "Buscar ahora",
        "fr": "Vérifier maintenant",
        "it": "Cerca ora",
        "pt-BR": "Verificar agora",
        "ja": "今すぐ確認",
        "zh-Hans": "立即检查",
        "zh-Hant": "立即檢查",
        "ko": "지금 확인",
        "hi": "अभी देखें",
        "ru": "Проверить сейчас",
        "pl": "Sprawdź teraz",
        "nl": "Controleer nu",
        "ar": "التحقّق الآن",
        "fa": "بررسی کن",
        "he": "בדוק עכשיו",
    },
    "Clear all emoji usage stats?": {
        "en-GB": "Clear all emoji usage stats?",
        "de": "Alle Emoji-Nutzungsstatistiken löschen?",
        "es": "¿Borrar todas las estadísticas de uso de emoji?",
        "es-419": "¿Borrar todas las estadísticas de uso de emojis?",
        "fr": "Effacer toutes les statistiques d'utilisation des emoji ?",
        "it": "Vuoi cancellare tutte le statistiche di utilizzo delle emoji?",
        "pt-BR": "Apagar todas as estatísticas de uso de emoji?",
        "ja": "すべての絵文字使用統計を削除しますか?",
        "zh-Hans": "清除所有 emoji 使用统计?",
        "zh-Hant": "清除所有 emoji 使用統計?",
        "ko": "모든 이모지 사용 통계를 지울까요?",
        "hi": "क्या सभी इमोजी उपयोग आँकड़े हटा दें?",
        "ru": "Очистить всю статистику использования эмодзи?",
        "pl": "Wyczyścić wszystkie statystyki użycia emoji?",
        "nl": "Alle emoji-statistieken wissen?",
        "ar": "هل تريد مسح كل إحصاءات استخدام الإيموجي؟",
        "fa": "همهٔ آمار استفاده از ایموجی پاک شود؟",
        "he": "לנקות את כל סטטיסטיקות השימוש באימוג'י?",
    },
    "Clear stats": {
        "en-GB": "Clear stats",
        "de": "Statistiken löschen",
        "es": "Borrar estadísticas",
        "es-419": "Borrar estadísticas",
        "fr": "Effacer les stats",
        "it": "Cancella statistiche",
        "pt-BR": "Apagar estatísticas",
        "ja": "統計を削除",
        "zh-Hans": "清除统计",
        "zh-Hant": "清除統計",
        "ko": "통계 지우기",
        "hi": "आँकड़े हटाएँ",
        "ru": "Очистить статистику",
        "pl": "Wyczyść statystyki",
        "nl": "Wis statistieken",
        "ar": "مسح الإحصاءات",
        "fa": "پاک‌کردن آمار",
        "he": "נקה סטטיסטיקות",
    },
    "Clear stats...": {
        "en-GB": "Clear stats…",
        "de": "Statistiken löschen…",
        "es": "Borrar estadísticas…",
        "es-419": "Borrar estadísticas…",
        "fr": "Effacer les stats…",
        "it": "Cancella statistiche…",
        "pt-BR": "Apagar estatísticas…",
        "ja": "統計を削除…",
        "zh-Hans": "清除统计…",
        "zh-Hant": "清除統計…",
        "ko": "통계 지우기…",
        "hi": "आँकड़े हटाएँ…",
        "ru": "Очистить статистику…",
        "pl": "Wyczyść statystyki…",
        "nl": "Wis statistieken…",
        "ar": "مسح الإحصاءات…",
        "fa": "پاک‌کردن آمار…",
        "he": "נקה סטטיסטיקות…",
    },
    "Continue": {
        "en-GB": "Continue",
        "de": "Weiter",
        "es": "Continuar",
        "es-419": "Continuar",
        "fr": "Continuer",
        "it": "Continua",
        "pt-BR": "Continuar",
        "ja": "続ける",
        "zh-Hans": "继续",
        "zh-Hant": "繼續",
        "ko": "계속",
        "hi": "जारी रखें",
        "ru": "Продолжить",
        "pl": "Kontynuuj",
        "nl": "Ga door",
        "ar": "متابعة",
        "fa": "ادامه",
        "he": "המשך",
    },
    "Convert emoticons (`:D` → 😃)": {
        "en-GB": "Convert emoticons (`:D` → 😃)",
        "de": "Emoticons umwandeln (`:D` → 😃)",
        "es": "Convertir emoticonos (`:D` → 😃)",
        "es-419": "Convertir emoticones (`:D` → 😃)",
        "fr": "Convertir les émoticônes (`:D` → 😃)",
        "it": "Converti le emoticon (`:D` → 😃)",
        "pt-BR": "Converter emoticons (`:D` → 😃)",
        "ja": "顔文字を変換 (`:D` → 😃)",
        "zh-Hans": "转换颜文字 (`:D` → 😃)",
        "zh-Hant": "轉換顏文字 (`:D` → 😃)",
        "ko": "이모티콘 변환 (`:D` → 😃)",
        "hi": "इमोटिकॉन बदलें (`:D` → 😃)",
        "ru": "Преобразовывать эмотиконы (`:D` → 😃)",
        "pl": "Konwertuj emotikony (`:D` → 😃)",
        "nl": "Zet emoticons om (`:D` → 😃)",
        "ar": "تحويل الرموز التعبيرية النصّية (`:D` → 😃)",
        "fa": "تبدیل شکلک‌ها (`:D` → 😃)",
        "he": "המר אמוטיקונים (`:D` → 😃)",
    },
    "Copied!": {
        "en-GB": "Copied!",
        "de": "Kopiert!",
        "es": "¡Copiado!",
        "es-419": "¡Copiado!",
        "fr": "Copié !",
        "it": "Copiato!",
        "pt-BR": "Copiado!",
        "ja": "コピーしました!",
        "zh-Hans": "已复制!",
        "zh-Hant": "已複製!",
        "ko": "복사됨!",
        "hi": "कॉपी हो गया!",
        "ru": "Скопировано!",
        "pl": "Skopiowano!",
        "nl": "Gekopieerd!",
        "ar": "تم النسخ!",
        "fa": "کپی شد!",
        "he": "הועתק!",
    },
    "Copy": {
        "en-GB": "Copy",
        "de": "Kopieren",
        "es": "Copiar",
        "es-419": "Copiar",
        "fr": "Copier",
        "it": "Copia",
        "pt-BR": "Copiar",
        "ja": "コピー",
        "zh-Hans": "复制",
        "zh-Hant": "複製",
        "ko": "복사",
        "hi": "कॉपी करें",
        "ru": "Копировать",
        "pl": "Kopiuj",
        "nl": "Kopieer",
        "ar": "نسخ",
        "fa": "کپی",
        "he": "העתק",
    },
    "Add a Giphy API key to enable GIF search.": {
        "en-GB": "Add a Giphy API key to enable GIF search.",
        "de": "Füge einen Giphy-API-Schlüssel hinzu, um die GIF-Suche zu aktivieren.",
        "es": "Añade una clave de la API de Giphy para activar la búsqueda de GIF.",
        "es-419": "Agregá una clave de la API de Giphy para activar la búsqueda de GIF.",
        "fr": "Ajoute une clé d'API Giphy pour activer la recherche de GIF.",
        "it": "Aggiungi una chiave API di Giphy per attivare la ricerca di GIF.",
        "pt-BR": "Adicione uma chave da API do Giphy para ativar a busca de GIF.",
        "ja": "GIF 検索を有効にするには、Giphy の API キーを追加してください。",
        "zh-Hans": "添加 Giphy API 密钥以启用 GIF 搜索。",
        "zh-Hant": "新增 Giphy API 金鑰以啟用 GIF 搜尋。",
        "ko": "GIF 검색을 사용하려면 Giphy API 키를 추가하세요.",
        "hi": "GIF खोज सक्षम करने के लिए Giphy API कुंजी जोड़ें।",
        "ru": "Добавьте ключ API Giphy, чтобы включить поиск GIF.",
        "pl": "Dodaj klucz API Giphy, aby włączyć wyszukiwanie GIF-ów.",
        "nl": "Voeg een Giphy API-sleutel toe om GIF-zoeken aan te zetten.",
        "ar": "أضف مفتاح Giphy API لتفعيل البحث عن GIF.",
        "fa": "برای فعال‌سازی جست‌وجوی GIF، یک کلید API Giphy اضافه کنید.",
        "he": "הוסף מפתח Giphy API כדי להפעיל חיפוש GIF.",
    },
    "Load more": {
        "en-GB": "Load more",
        "de": "Mehr laden",
        "es": "Cargar más",
        "es-419": "Cargar más",
        "fr": "Charger plus",
        "it": "Carica altri",
        "pt-BR": "Carregar mais",
        "ja": "さらに読み込む",
        "zh-Hans": "加载更多",
        "zh-Hant": "載入更多",
        "ko": "더 불러오기",
        "hi": "और लोड करें",
        "ru": "Загрузить ещё",
        "pl": "Załaduj więcej",
        "nl": "Meer laden",
        "ar": "تحميل المزيد",
        "fa": "بارگذاری بیشتر",
        "he": "טען עוד",
    },
    "GIFs and Symbols": {
        "en-GB": "GIFs and Symbols",
        "de": "GIFs und Symbole",
        "es": "GIF y símbolos",
        "es-419": "GIF y símbolos",
        "fr": "GIF et symboles",
        "it": "GIF e simboli",
        "pt-BR": "GIFs e símbolos",
        "ja": "GIF と記号",
        "zh-Hans": "GIF 和符号",
        "zh-Hant": "GIF 與符號",
        "ko": "GIF 및 기호",
        "hi": "GIF और प्रतीक",
        "ru": "GIF и символы",
        "pl": "GIF-y i symbole",
        "nl": "GIFs en symbolen",
        "ar": "صور GIF والرموز",
        "fa": "گیف‌ها و نمادها",
        "he": "GIF-ים וסמלים",
    },
    "GIF search": {
        "en-GB": "GIF search",
        "de": "GIF-Suche",
        "es": "Búsqueda de GIF",
        "es-419": "Búsqueda de GIF",
        "fr": "Recherche de GIF",
        "it": "Ricerca GIF",
        "pt-BR": "Busca de GIF",
        "ja": "GIF 検索",
        "zh-Hans": "GIF 搜索",
        "zh-Hant": "GIF 搜尋",
        "ko": "GIF 검색",
        "hi": "GIF खोज",
        "ru": "Поиск GIF",
        "pl": "Wyszukiwanie GIF-ów",
        "nl": "GIF-zoeken",
        "ar": "البحث عن GIF",
        "fa": "جست‌وجوی GIF",
        "he": "חיפוש GIF",
    },
    "Type `:::` then a search term to insert a GIF from Giphy.": {
        "en-GB": "Type `:::` then a search term to insert a GIF from Giphy.",
        "de": "Tippe `:::` und dann einen Suchbegriff, um ein GIF von Giphy einzufügen.",
        "es": "Escribe `:::` seguido de un término de búsqueda para insertar un GIF de Giphy.",
        "es-419": "Escribí `:::` seguido de un término de búsqueda para insertar un GIF de Giphy.",
        "fr": "Tape `:::` puis un terme de recherche pour insérer un GIF depuis Giphy.",
        "it": "Digita `:::` seguito da un termine di ricerca per inserire un GIF da Giphy.",
        "pt-BR": "Digite `:::` e depois um termo de busca para inserir um GIF do Giphy.",
        "ja": "`:::` の後に検索語を入力すると、Giphy から GIF を挿入できます。",
        "zh-Hans": "输入 `:::` 后跟搜索词,从 Giphy 插入 GIF。",
        "zh-Hant": "輸入 `:::` 後接搜尋字詞,即可從 Giphy 插入 GIF。",
        "ko": "`:::` 다음에 검색어를 입력하면 Giphy에서 GIF를 삽입합니다.",
        "hi": "Giphy से GIF डालने के लिए `:::` के बाद कोई खोज शब्द टाइप करें।",
        "ru": "Введите `:::` и поисковый запрос, чтобы вставить GIF из Giphy.",
        "pl": "Wpisz `:::`, a następnie szukane hasło, aby wstawić GIF z Giphy.",
        "nl": "Typ `:::` gevolgd door een zoekterm om een GIF van Giphy in te voegen.",
        "ar": "اكتب `:::` ثم كلمة بحث لإدراج صورة GIF من Giphy.",
        "fa": "‏`:::` و سپس یک عبارت جست‌وجو تایپ کنید تا یک GIF از Giphy درج شود.",
        "he": "הקלד `:::` ואז ביטוי חיפוש כדי להוסיף GIF מ-Giphy.",
    },
    "Symbols": {
        "en-GB": "Symbols",
        "de": "Symbole",
        "es": "Símbolos",
        "es-419": "Símbolos",
        "fr": "Symboles",
        "it": "Simboli",
        "pt-BR": "Símbolos",
        "ja": "記号",
        "zh-Hans": "符号",
        "zh-Hant": "符號",
        "ko": "기호",
        "hi": "प्रतीक",
        "ru": "Символы",
        "pl": "Symbole",
        "nl": "Symbolen",
        "ar": "الرموز",
        "fa": "نمادها",
        "he": "סמלים",
    },
    "Include ★ ⌘ ⌥ and similar characters in results (experimental).": {
        "en-GB": "Include ★ ⌘ ⌥ and similar characters in results (experimental).",
        "de": "★ ⌘ ⌥ und ähnliche Zeichen in den Ergebnissen anzeigen (experimentell).",
        "es": "Incluir ★ ⌘ ⌥ y caracteres similares en los resultados (experimental).",
        "es-419": "Incluir ★ ⌘ ⌥ y caracteres similares en los resultados (experimental).",
        "fr": "Inclure ★ ⌘ ⌥ et caractères similaires dans les résultats (expérimental).",
        "it": "Includi ★ ⌘ ⌥ e caratteri simili nei risultati (sperimentale).",
        "pt-BR": "Incluir ★ ⌘ ⌥ e caracteres semelhantes nos resultados (experimental).",
        "ja": "★ ⌘ ⌥ などの記号を結果に含めます(実験的)。",
        "zh-Hans": "在结果中包含 ★ ⌘ ⌥ 等字符(实验性)。",
        "zh-Hant": "在結果中包含 ★ ⌘ ⌥ 等字元(實驗性)。",
        "ko": "★ ⌘ ⌥ 등 유사 문자를 결과에 포함합니다(실험적).",
        "hi": "परिणामों में ★ ⌘ ⌥ और मिलते-जुलते वर्ण शामिल करें (प्रयोगात्मक)।",
        "ru": "Включать ★ ⌘ ⌥ и подобные символы в результаты (экспериментально).",
        "pl": "Uwzględniaj ★ ⌘ ⌥ i podobne znaki w wynikach (eksperymentalne).",
        "nl": "Toon ★ ⌘ ⌥ en vergelijkbare tekens in resultaten (experimenteel).",
        "ar": "تضمين ★ ⌘ ⌥ والأحرف المشابهة في النتائج (تجريبي).",
        "fa": "گنجاندن ★ ⌘ ⌥ و کاراکترهای مشابه در نتایج (آزمایشی).",
        "he": "כלול את ★ ⌘ ⌥ ותווים דומים בתוצאות (ניסיוני).",
    },
    "GIF search bypass": {
        "en-GB": "GIF search bypass",
        "de": "GIF-Suche ohne Ausschlüsse",
        "es": "Excepción para búsqueda de GIF",
        "es-419": "Excepción para búsqueda de GIF",
        "fr": "Exception pour la recherche de GIF",
        "it": "Eccezione per la ricerca di GIF",
        "pt-BR": "Exceção para a busca de GIF",
        "ja": "GIF 検索の例外",
        "zh-Hans": "GIF 搜索例外",
        "zh-Hant": "GIF 搜尋例外",
        "ko": "GIF 검색 예외",
        "hi": "GIF खोज अपवाद",
        "ru": "Исключение для поиска GIF",
        "pl": "Wyjątek dla wyszukiwania GIF",
        "nl": "GIF-zoeken uitzondering",
        "ar": "استثناء البحث عن GIF",
        "fa": "استثنای جست‌وجوی GIF",
        "he": "חריגה לחיפוש GIF",
    },
    "Let GIF search work in excluded apps": {
        "en-GB": "Let GIF search work in excluded apps",
        "de": "GIF-Suche auch in ausgeschlossenen Apps zulassen",
        "es": "Permitir la búsqueda de GIF en apps excluidas",
        "es-419": "Permitir la búsqueda de GIF en apps excluidas",
        "fr": "Autoriser la recherche de GIF dans les apps exclues",
        "it": "Consenti la ricerca di GIF nelle app escluse",
        "pt-BR": "Permitir busca de GIF em apps excluídos",
        "ja": "除外したアプリでも GIF 検索を有効にする",
        "zh-Hans": "在已排除的应用中也启用 GIF 搜索",
        "zh-Hant": "在已排除的 App 中仍允許 GIF 搜尋",
        "ko": "제외된 앱에서도 GIF 검색 허용",
        "hi": "बहिष्कृत ऐप्स में भी GIF खोज की अनुमति दें",
        "ru": "Разрешать поиск GIF в исключённых приложениях",
        "pl": "Zezwalaj na wyszukiwanie GIF-ów w wykluczonych aplikacjach",
        "nl": "GIF-zoeken toestaan in uitgesloten apps",
        "ar": "السماح بالبحث عن GIF في التطبيقات المستثناة",
        "fa": "اجازه دادن جست‌وجوی GIF در برنامه‌های مستثنا",
        "he": "אפשר חיפוש GIF גם באפליקציות מוחרגות",
    },
    "`:::` overrides the exclusion list.": {
        "en-GB": "`:::` overrides the exclusion list.",
        "de": "`:::` umgeht die Ausschlussliste.",
        "es": "`:::` ignora la lista de exclusiones.",
        "es-419": "`:::` ignora la lista de exclusiones.",
        "fr": "`:::` ignore la liste d'exclusions.",
        "it": "`:::` ignora l'elenco delle esclusioni.",
        "pt-BR": "`:::` ignora a lista de exclusões.",
        "ja": "`:::` は除外リストを無視します。",
        "zh-Hans": "`:::` 会忽略排除列表。",
        "zh-Hant": "`:::` 會略過排除清單。",
        "ko": "`:::`은(는) 제외 목록을 무시합니다.",
        "hi": "`:::` बहिष्कार सूची को नज़रअंदाज़ करता है।",
        "ru": "`:::` обходит список исключений.",
        "pl": "`:::` pomija listę wykluczeń.",
        "nl": "`:::` negeert de uitsluitingslijst.",
        "ar": "‏`:::` يتجاوز قائمة الاستثناءات.",
        "fa": "‏`:::` فهرست استثناها را نادیده می‌گیرد.",
        "he": "‏`:::` עוקף את רשימת ההחרגות.",
    },
    "Couldn't reach Giphy.": {
        "en-GB": "Couldn't reach Giphy.",
        "de": "Giphy nicht erreichbar.",
        "es": "No se pudo conectar con Giphy.",
        "es-419": "No se pudo conectar con Giphy.",
        "fr": "Impossible de joindre Giphy.",
        "it": "Impossibile raggiungere Giphy.",
        "pt-BR": "Não foi possível acessar o Giphy.",
        "ja": "Giphy に接続できませんでした。",
        "zh-Hans": "无法连接到 Giphy。",
        "zh-Hant": "無法連線到 Giphy。",
        "ko": "Giphy에 연결할 수 없습니다.",
        "hi": "Giphy तक नहीं पहुँचा जा सका।",
        "ru": "Не удалось связаться с Giphy.",
        "pl": "Nie udało się połączyć z Giphy.",
        "nl": "Kon Giphy niet bereiken.",
        "ar": "تعذّر الوصول إلى Giphy.",
        "fa": "اتصال به Giphy ممکن نشد.",
        "he": "לא ניתן להתחבר ל-Giphy.",
    },
    "Giphy rejected the API key.": {
        "en-GB": "Giphy rejected the API key.",
        "de": "Giphy hat den API-Schlüssel abgelehnt.",
        "es": "Giphy rechazó la clave de la API.",
        "es-419": "Giphy rechazó la clave de la API.",
        "fr": "Giphy a refusé la clé d'API.",
        "it": "Giphy ha rifiutato la chiave API.",
        "pt-BR": "O Giphy rejeitou a chave da API.",
        "ja": "Giphy が API キーを拒否しました。",
        "zh-Hans": "Giphy 拒绝了 API 密钥。",
        "zh-Hant": "Giphy 拒絕了 API 金鑰。",
        "ko": "Giphy가 API 키를 거부했습니다.",
        "hi": "Giphy ने API कुंजी अस्वीकार कर दी।",
        "ru": "Giphy отклонил ключ API.",
        "pl": "Giphy odrzuciło klucz API.",
        "nl": "Giphy weigerde de API-sleutel.",
        "ar": "رفض Giphy مفتاح API.",
        "fa": "‏Giphy کلید API را رد کرد.",
        "he": "‏Giphy דחתה את מפתח ה-API.",
    },
    "Giphy responded with an unexpected result.": {
        "en-GB": "Giphy responded with an unexpected result.",
        "de": "Giphy hat unerwartet geantwortet.",
        "es": "Giphy respondió con un resultado inesperado.",
        "es-419": "Giphy respondió con un resultado inesperado.",
        "fr": "Giphy a répondu avec un résultat inattendu.",
        "it": "Giphy ha risposto con un risultato inatteso.",
        "pt-BR": "O Giphy retornou um resultado inesperado.",
        "ja": "Giphy から予期しない応答が返されました。",
        "zh-Hans": "Giphy 返回了意外的结果。",
        "zh-Hant": "Giphy 回傳了預期外的結果。",
        "ko": "Giphy가 예상치 못한 응답을 보냈습니다.",
        "hi": "Giphy से अप्रत्याशित प्रतिक्रिया मिली।",
        "ru": "Giphy вернул неожиданный ответ.",
        "pl": "Giphy zwróciło nieoczekiwany wynik.",
        "nl": "Giphy gaf een onverwacht resultaat.",
        "ar": "ردّ Giphy بنتيجة غير متوقعة.",
        "fa": "‏Giphy پاسخی غیرمنتظره برگرداند.",
        "he": "‏Giphy החזירה תוצאה לא צפויה.",
    },
    "No GIFs found.": {
        "en-GB": "No GIFs found.",
        "de": "Keine GIFs gefunden.",
        "es": "No se han encontrado GIF.",
        "es-419": "No se encontraron GIF.",
        "fr": "Aucun GIF trouvé.",
        "it": "Nessun GIF trovato.",
        "pt-BR": "Nenhum GIF encontrado.",
        "ja": "GIF が見つかりませんでした。",
        "zh-Hans": "没有找到 GIF。",
        "zh-Hant": "找不到 GIF。",
        "ko": "GIF를 찾을 수 없습니다.",
        "hi": "कोई GIF नहीं मिला।",
        "ru": "GIF не найдены.",
        "pl": "Nie znaleziono GIF-ów.",
        "nl": "Geen GIFs gevonden.",
        "ar": "لم يُعثر على أي GIF.",
        "fa": "هیچ GIF‌ای پیدا نشد.",
        "he": "לא נמצאו GIF-ים.",
    },
    "Search GIFs…": {
        "en-GB": "Search GIFs…",
        "de": "GIFs suchen…",
        "es": "Buscar GIF…",
        "es-419": "Buscar GIF…",
        "fr": "Rechercher des GIF…",
        "it": "Cerca GIF…",
        "pt-BR": "Buscar GIF…",
        "ja": "GIF を検索…",
        "zh-Hans": "搜索 GIF…",
        "zh-Hant": "搜尋 GIF…",
        "ko": "GIF 검색…",
        "hi": "GIF खोजें…",
        "ru": "Найти GIF…",
        "pl": "Szukaj GIF-ów…",
        "nl": "Zoek GIFs…",
        "ar": "البحث عن GIF…",
        "fa": "جست‌وجوی GIF…",
        "he": "חפש GIF…",
    },
    "Searching…": {
        "en-GB": "Searching…",
        "de": "Suche läuft…",
        "es": "Buscando…",
        "es-419": "Buscando…",
        "fr": "Recherche…",
        "it": "Ricerca in corso…",
        "pt-BR": "Buscando…",
        "ja": "検索中…",
        "zh-Hans": "搜索中…",
        "zh-Hant": "搜尋中…",
        "ko": "검색 중…",
        "hi": "खोजा जा रहा है…",
        "ru": "Идёт поиск…",
        "pl": "Wyszukiwanie…",
        "nl": "Zoeken…",
        "ar": "جارٍ البحث…",
        "fa": "در حال جست‌وجو…",
        "he": "מחפש…",
    },
    "Type to search GIFs.": {
        "en-GB": "Type to search GIFs.",
        "de": "Tippe, um GIFs zu suchen.",
        "es": "Escribe para buscar GIF.",
        "es-419": "Escribí para buscar GIF.",
        "fr": "Tape pour rechercher des GIF.",
        "it": "Digita per cercare GIF.",
        "pt-BR": "Digite para buscar GIF.",
        "ja": "GIF を検索するには入力してください。",
        "zh-Hans": "输入以搜索 GIF。",
        "zh-Hant": "輸入以搜尋 GIF。",
        "ko": "GIF를 검색하려면 입력하세요.",
        "hi": "GIF खोजने के लिए टाइप करें।",
        "ru": "Введите запрос для поиска GIF.",
        "pl": "Wpisz, aby wyszukać GIF-y.",
        "nl": "Typ om GIFs te zoeken.",
        "ar": "اكتب للبحث عن GIF.",
        "fa": "برای جست‌وجوی GIF تایپ کنید.",
        "he": "הקלד כדי לחפש GIF-ים.",
    },
    "copy": {
        # Lowercase footer-hint variant (GIF picker bottom bar).
        "en-GB": "copy",
        "de": "kopieren",
        "es": "copiar",
        "es-419": "copiar",
        "fr": "copier",
        "it": "copia",
        "pt-BR": "copiar",
        "ja": "コピー",
        "zh-Hans": "复制",
        "zh-Hant": "複製",
        "ko": "복사",
        "hi": "कॉपी",
        "ru": "копировать",
        "pl": "kopiuj",
        "nl": "kopieer",
        "ar": "نسخ",
        "fa": "کپی",
        "he": "העתק",
    },
    "navigate": {
        "en-GB": "navigate",
        "de": "navigieren",
        "es": "navegar",
        "es-419": "navegar",
        "fr": "naviguer",
        "it": "naviga",
        "pt-BR": "navegar",
        "ja": "移動",
        "zh-Hans": "移动",
        "zh-Hant": "移動",
        "ko": "이동",
        "hi": "नेविगेट",
        "ru": "перемещение",
        "pl": "nawiguj",
        "nl": "navigeer",
        "ar": "تنقّل",
        "fa": "حرکت",
        "he": "ניווט",
    },
    "Danger zone": {
        "en-GB": "Danger zone",
        "de": "Gefahrenzone",
        "es": "Zona peligrosa",
        "es-419": "Zona peligrosa",
        "fr": "Zone à risque",
        "it": "Zona pericolosa",
        "pt-BR": "Zona de risco",
        "ja": "危険な操作",
        "zh-Hans": "危险区域",
        "zh-Hant": "危險區域",
        "ko": "주의 영역",
        "hi": "ख़तरे का क्षेत्र",
        "ru": "Опасная зона",
        "pl": "Strefa ryzyka",
        "nl": "Gevaarlijke zone",
        "ar": "منطقة الخطر",
        "fa": "منطقهٔ خطر",
        "he": "אזור מסוכן",
    },
    "Donate": {
        "en-GB": "Donate",
        "de": "Spenden",
        "es": "Donar",
        "es-419": "Donar",
        "fr": "Faire un don",
        "it": "Dona",
        "pt-BR": "Doar",
        "ja": "寄付する",
        "zh-Hans": "捐赠",
        "zh-Hant": "贊助",
        "ko": "후원",
        "hi": "दान करें",
        "ru": "Поддержать",
        "pl": "Wpłać",
        "nl": "Doneer",
        "ar": "تبرّع",
        "fa": "حمایت",
        "he": "תרום",
    },
    "Done": {
        "en-GB": "Done",
        "de": "Fertig",
        "es": "Hecho",
        "es-419": "Listo",
        "fr": "Terminé",
        "it": "Fatto",
        "pt-BR": "Concluído",
        "ja": "完了",
        "zh-Hans": "完成",
        "zh-Hant": "完成",
        "ko": "완료",
        "hi": "हो गया",
        "ru": "Готово",
        "pl": "Gotowe",
        "nl": "Klaar",
        "ar": "تم",
        "fa": "تمام",
        "he": "סיום",
    },
    "Easter egg discovered": {
        "en-GB": "Easter egg discovered",
        "de": "Easter Egg entdeckt",
        "es": "Huevo de pascua descubierto",
        "es-419": "Huevo de pascua descubierto",
        "fr": "Easter egg découvert",
        "it": "Easter egg scoperto",
        "pt-BR": "Easter egg descoberto",
        "ja": "イースターエッグを発見",
        "zh-Hans": "发现彩蛋",
        "zh-Hant": "發現彩蛋",
        "ko": "이스터에그 발견",
        "hi": "ईस्टर एग मिला",
        "ru": "Найдена пасхалка",
        "pl": "Odkryto easter egg",
        "nl": "Easter egg gevonden",
        "ar": "تم اكتشاف بيضة مفاجِئة",
        "fa": "تخم‌مرغ نوروزی پیدا شد",
        "he": "התגלתה ביצת פסחא",
    },
    "Easter eggs": {
        "en-GB": "Easter eggs",
        "de": "Easter Eggs",
        "es": "Huevos de pascua",
        "es-419": "Huevos de pascua",
        "fr": "Easter eggs",
        "it": "Easter egg",
        "pt-BR": "Easter eggs",
        "ja": "イースターエッグ",
        "zh-Hans": "彩蛋",
        "zh-Hant": "彩蛋",
        "ko": "이스터에그",
        "hi": "ईस्टर एग",
        "ru": "Пасхалки",
        "pl": "Easter eggs",
        "nl": "Easter eggs",
        "ar": "بيوض مفاجِئة",
        "fa": "تخم‌مرغ‌های نوروزی",
        "he": "ביצי פסחא",
    },
    "Emoji": {
        "en-GB": "Emoji",
        "de": "Emoji",
        "es": "Emoji",
        "es-419": "Emoji",
        "fr": "Émoji",
        "it": "Emoji",
        "pt-BR": "Emoji",
        "ja": "絵文字",
        "zh-Hans": "Emoji",
        "zh-Hant": "Emoji",
        "ko": "이모지",
        "hi": "इमोजी",
        "ru": "Эмодзи",
        "pl": "Emoji",
        "nl": "Emoji",
        "ar": "إيموجي",
        "fa": "ایموجی",
        "he": "אימוג'י",
    },
    "Emoji autocompleted": {
        "en-GB": "Emoji autocompleted",
        "de": "Vervollständigte Emoji",
        "es": "Emoji autocompletados",
        "es-419": "Emojis autocompletados",
        "fr": "Émoji autocomplétés",
        "it": "Emoji completati",
        "pt-BR": "Emoji autocompletados",
        "ja": "自動補完した絵文字",
        "zh-Hans": "已自动补全 emoji",
        "zh-Hant": "已自動完成 emoji",
        "ko": "자동 완성된 이모지",
        "hi": "ऑटोकम्प्लीट किए गए इमोजी",
        "ru": "Эмодзи добавлено",
        "pl": "Uzupełnione emoji",
        "nl": "Aangevulde emoji",
        "ar": "إيموجي تمّ إكمالها تلقائياً",
        "fa": "ایموجی‌های تکمیل‌شده",
        "he": "אימוג'י שהושלמו",
    },
    "Exclusions": {
        "en-GB": "Exclusions",
        "de": "Ausnahmen",
        "es": "Exclusiones",
        "es-419": "Exclusiones",
        "fr": "Exclusions",
        "it": "Esclusioni",
        "pt-BR": "Exclusões",
        "ja": "除外",
        "zh-Hans": "排除项",
        "zh-Hant": "排除項目",
        "ko": "제외 항목",
        "hi": "अपवर्जन",
        "ru": "Исключения",
        "pl": "Wykluczenia",
        "nl": "Uitsluitingen",
        "ar": "الاستثناءات",
        "fa": "موارد مستثنا",
        "he": "החרגות",
    },
    "Funded by donations": {
        "en-GB": "Funded by donations",
        "de": "Durch Spenden finanziert",
        "es": "Financiado con donaciones",
        "es-419": "Financiado con donaciones",
        "fr": "Financé par les dons",
        "it": "Finanziato dalle donazioni",
        "pt-BR": "Financiado por doações",
        "ja": "寄付で支えられています",
        "zh-Hans": "由捐赠资助",
        "zh-Hant": "由贊助支持",
        "ko": "후원으로 운영",
        "hi": "दान से वित्तपोषित",
        "ru": "Существует на пожертвования",
        "pl": "Finansowane z wpłat",
        "nl": "Gefinancierd door donaties",
        "ar": "تموَّل من التبرّعات",
        "fa": "با حمایت‌های مردمی",
        "he": "ממומן בתרומות",
    },
    "General": {
        "en-GB": "General",
        "de": "Allgemein",
        "es": "General",
        "es-419": "General",
        "fr": "Général",
        "it": "Generali",
        "pt-BR": "Geral",
        "ja": "一般",
        "zh-Hans": "通用",
        "zh-Hant": "一般",
        "ko": "일반",
        "hi": "सामान्य",
        "ru": "Основные",
        "pl": "Ogólne",
        "nl": "Algemeen",
        "ar": "عام",
        "fa": "عمومی",
        "he": "כללי",
    },
    "Get started": {
        "en-GB": "Get started",
        "de": "Los geht's",
        "es": "Empezar",
        "es-419": "Empezar",
        "fr": "Commencer",
        "it": "Inizia",
        "pt-BR": "Começar",
        "ja": "はじめる",
        "zh-Hans": "开始使用",
        "zh-Hant": "開始使用",
        "ko": "시작하기",
        "hi": "शुरू करें",
        "ru": "Начать",
        "pl": "Rozpocznij",
        "nl": "Aan de slag",
        "ar": "ابدأ",
        "fa": "شروع کنید",
        "he": "התחל",
    },
    "Grant accessibility permissions": {
        "en-GB": "Grant accessibility permissions",
        "de": "Bedienungshilfen-Berechtigungen erteilen",
        "es": "Conceder permisos de accesibilidad",
        "es-419": "Otorgar permisos de accesibilidad",
        "fr": "Accorder les autorisations d'accessibilité",
        "it": "Concedi i permessi di accessibilità",
        "pt-BR": "Conceder permissões de acessibilidade",
        "ja": "アクセシビリティの権限を許可",
        "zh-Hans": "授予辅助功能权限",
        "zh-Hant": "授予輔助使用權限",
        "ko": "손쉬운 사용 권한 허용",
        "hi": "ऐक्सेसिबिलिटी अनुमतियाँ दें",
        "ru": "Предоставьте разрешения универсального доступа",
        "pl": "Udziel uprawnień dostępności",
        "nl": "Geef toegankelijkheidstoestemmingen",
        "ar": "منح أذونات إمكانية الوصول",
        "fa": "اعطای دسترسی به دسترس‌پذیری",
        "he": "אשר הרשאות נגישות",
    },
    "I donated": {
        "en-GB": "I donated",
        "de": "Ich habe gespendet",
        "es": "Ya he donado",
        "es-419": "Ya doné",
        "fr": "J'ai fait un don",
        "it": "Ho donato",
        "pt-BR": "Eu doei",
        "ja": "寄付しました",
        "zh-Hans": "我已捐赠",
        "zh-Hant": "我已贊助",
        "ko": "후원했어요",
        "hi": "मैंने दान किया",
        "ru": "Я поддержал",
        "pl": "Wpłaciłem(-am)",
        "nl": "Ik heb gedoneerd",
        "ar": "لقد تبرّعت",
        "fa": "حمایت کردم",
        "he": "תרמתי",
    },
    "If the icon doesn't appear in the menu bar, check **System Settings → Menu Bar → \"Allow in the Menu Bar\"**.": {
        "en-GB": "If the icon doesn't appear in the menu bar, check **System Settings → Menu Bar → \"Allow in the Menu Bar\"**.",
        "de": "Falls das Symbol nicht in der Menüleiste erscheint, prüfe **Systemeinstellungen → Menüleiste → „In der Menüleiste erlauben\"**.",
        "es": "Si el icono no aparece en la barra de menús, revisa **Ajustes del sistema → Barra de menús → \"Permitir en la barra de menús\"**.",
        "es-419": "Si el ícono no aparece en la barra de menús, revisá **Ajustes del sistema → Barra de menús → \"Permitir en la barra de menús\"**.",
        "fr": "Si l'icône n'apparaît pas dans la barre de menus, vérifie **Réglages Système → Barre de menus → « Autoriser dans la barre de menus »**.",
        "it": "Se l'icona non compare nella barra dei menu, controlla **Impostazioni di Sistema → Barra dei menu → \"Consenti nella barra dei menu\"**.",
        "pt-BR": "Se o ícone não aparecer na barra de menus, confira **Ajustes do Sistema → Barra de Menus → \"Permitir na barra de menus\"**.",
        "ja": "メニューバーにアイコンが表示されない場合は、**システム設定 → メニューバー → \"メニューバーで許可\"** を確認してください。",
        "zh-Hans": "如果图标没有出现在菜单栏中,请检查 **系统设置 → 菜单栏 → \"在菜单栏中允许\"**。",
        "zh-Hant": "如果圖示沒有出現在選單列中,請檢查 **系統設定 → 選單列 → \"允許在選單列中顯示\"**。",
        "ko": "메뉴 막대에 아이콘이 보이지 않으면 **시스템 설정 → 메뉴 막대 → \"메뉴 막대에서 허용\"** 을 확인하세요.",
        "hi": "अगर मेन्यू बार में आइकन नहीं दिखे, तो **सिस्टम सेटिंग्स → मेन्यू बार → \"मेन्यू बार में अनुमति दें\"** देखें।",
        "ru": "Если значок не появляется в строке меню, проверьте **Системные настройки → Строка меню → «Разрешить в строке меню»**.",
        "pl": "Jeśli ikona nie pojawia się na pasku menu, sprawdź **Ustawienia systemowe → Pasek menu → „Zezwól na pasku menu\"**.",
        "nl": "Als het pictogram niet in de menubalk verschijnt, controleer **Systeeminstellingen → Menubalk → \"Toestaan in menubalk\"**.",
        "ar": "إذا لم تظهر الأيقونة في شريط القوائم، تحقّق من **إعدادات النظام ← شريط القوائم ← \"السماح في شريط القوائم\"**.",
        "fa": "اگر آیکون در نوار منو ظاهر نشد، **تنظیمات سیستم ← نوار منو ← «اجازه در نوار منو»** را بررسی کنید.",
        "he": "אם הצלמית לא מופיעה בשורת התפריטים, בדוק את **הגדרות המערכת ← שורת התפריטים ← \"אפשר בשורת התפריטים\"**.",
    },
    "Include symbols (experimental)": {
        "en-GB": "Include symbols (experimental)",
        "de": "Symbole einbeziehen (experimentell)",
        "es": "Incluir símbolos (experimental)",
        "es-419": "Incluir símbolos (experimental)",
        "fr": "Inclure les symboles (expérimental)",
        "it": "Includi simboli (sperimentale)",
        "pt-BR": "Incluir símbolos (experimental)",
        "ja": "記号を含める(実験的)",
        "zh-Hans": "包含符号(实验性)",
        "zh-Hant": "包含符號(實驗性)",
        "ko": "기호 포함 (실험적)",
        "hi": "प्रतीक शामिल करें (प्रायोगिक)",
        "ru": "Включать символы (экспериментально)",
        "pl": "Uwzględnij symbole (eksperymentalne)",
        "nl": "Symbolen meenemen (experimenteel)",
        "ar": "تضمين الرموز (تجريبي)",
        "fa": "گنجاندن نمادها (آزمایشی)",
        "he": "כלול סמלים (ניסיוני)",
    },
    "Input Monitoring": {
        "en-GB": "Input Monitoring",
        "de": "Eingabeüberwachung",
        "es": "Monitorización de entrada",
        "es-419": "Monitoreo de entrada",
        "fr": "Surveillance des entrées",
        "it": "Monitoraggio dell'input",
        "pt-BR": "Monitoramento de Entrada",
        "ja": "入力監視",
        "zh-Hans": "输入监控",
        "zh-Hant": "輸入監控",
        "ko": "입력 모니터링",
        "hi": "इनपुट मॉनिटरिंग",
        "ru": "Мониторинг ввода",
        "pl": "Monitorowanie wprowadzania",
        "nl": "Invoercontrole",
        "ar": "مراقبة الإدخال",
        "fa": "نظارت بر ورودی",
        "he": "ניטור קלט",
    },
    "Keyboard shortcuts": {
        "en-GB": "Keyboard shortcuts",
        "de": "Tastaturkürzel",
        "es": "Atajos de teclado",
        "es-419": "Atajos de teclado",
        "fr": "Raccourcis clavier",
        "it": "Scorciatoie da tastiera",
        "pt-BR": "Atalhos de teclado",
        "ja": "キーボードショートカット",
        "zh-Hans": "键盘快捷键",
        "zh-Hant": "鍵盤捷徑",
        "ko": "키보드 단축키",
        "hi": "कीबोर्ड शॉर्टकट",
        "ru": "Сочетания клавиш",
        "pl": "Skróty klawiszowe",
        "nl": "Toetscombinaties",
        "ar": "اختصارات لوحة المفاتيح",
        "fa": "میان‌برهای صفحه‌کلید",
        "he": "קיצורי מקלדת",
    },
    "Keystrokes aren't logged": {
        "en-GB": "Keystrokes aren't logged",
        "de": "Tastenanschläge werden nicht protokolliert",
        "es": "Las pulsaciones no se registran",
        "es-419": "Las pulsaciones no se registran",
        "fr": "Les frappes ne sont pas journalisées",
        "it": "Le digitazioni non vengono registrate",
        "pt-BR": "As teclas digitadas não são registradas",
        "ja": "キー入力は記録されません",
        "zh-Hans": "不会记录按键",
        "zh-Hant": "不會記錄按鍵",
        "ko": "키 입력은 기록되지 않습니다",
        "hi": "कीस्ट्रोक्स लॉग नहीं किए जाते",
        "ru": "Нажатия клавиш не записываются",
        "pl": "Naciśnięcia klawiszy nie są zapisywane",
        "nl": "Toetsaanslagen worden niet vastgelegd",
        "ar": "لا يتمّ تسجيل ضغطات المفاتيح",
        "fa": "ضربه‌های کلید ذخیره نمی‌شود",
        "he": "הקשות מקלדת אינן נשמרות",
    },
    "Lets %@ anchor the picker next to your text cursor.": {
        "en-GB": "Lets %@ anchor the picker next to your text cursor.",
        "de": "Erlaubt %@, den Picker neben deinem Textcursor zu verankern.",
        "es": "Permite que %@ ancle el selector junto al cursor de texto.",
        "es-419": "Permite que %@ ancle el selector junto al cursor de texto.",
        "fr": "Permet à %@ d'ancrer le sélecteur à côté de votre curseur de texte.",
        "it": "Permette a %@ di ancorare il selettore accanto al cursore di testo.",
        "pt-BR": "Permite que o %@ ancore o seletor ao lado do cursor de texto.",
        "ja": "%@ がピッカーをテキストカーソルの隣に固定できるようになります。",
        "zh-Hans": "让 %@ 把选取器锚定在文本光标旁。",
        "zh-Hant": "讓 %@ 將選取器固定在文字游標旁邊。",
        "ko": "%@이(가) 선택기를 텍스트 커서 옆에 고정할 수 있게 합니다.",
        "hi": "%@ को आपके टेक्स्ट कर्सर के बगल में पिकर लगाने देता है।",
        "ru": "Позволяет %@ закреплять окно подбора рядом с курсором.",
        "pl": "Pozwala aplikacji %@ umieszczać okno wyboru obok kursora.",
        "nl": "Laat %@ de kiezer naast je tekstcursor verankeren.",
        "ar": "يتيح لـ %@ تثبيت أداة الاختيار بجوار مؤشر النص.",
        "fa": "به %@ اجازه می‌دهد انتخابگر را کنار مکان‌نمای متن قرار دهد.",
        "he": "מאפשר ל-%@ לעגן את הבורר ליד סמן הטקסט.",
    },
    "Lets %@ watch keystrokes for `:` triggers. Nothing is logged.": {
        "en-GB": "Lets %@ watch keystrokes for `:` triggers. Nothing is logged.",
        "de": "Erlaubt %@, Tastenanschläge auf `:` zu beobachten. Es wird nichts protokolliert.",
        "es": "Permite que %@ vigile las pulsaciones en busca del `:`. No se registra nada.",
        "es-419": "Permite que %@ vigile las pulsaciones en busca del `:`. No se registra nada.",
        "fr": "Permet à %@ de surveiller les frappes pour détecter `:`. Rien n'est journalisé.",
        "it": "Permette a %@ di osservare le digitazioni in cerca di `:`. Nulla viene registrato.",
        "pt-BR": "Permite que o %@ observe as teclas em busca de `:`. Nada é registrado.",
        "ja": "%@ が `:` のキー入力を監視できるようにします。何も記録されません。",
        "zh-Hans": "让 %@ 监听 `:` 触发键。不会记录任何内容。",
        "zh-Hant": "讓 %@ 監聽 `:` 觸發鍵。不會記錄任何內容。",
        "ko": "%@이(가) `:` 입력을 감지하도록 합니다. 아무것도 기록되지 않습니다.",
        "hi": "%@ को `:` के लिए कीस्ट्रोक देखने देता है। कुछ भी लॉग नहीं होता।",
        "ru": "Позволяет %@ отслеживать нажатия `:`. Ничего не записывается.",
        "pl": "Pozwala aplikacji %@ obserwować naciśnięcia `:`. Nic nie jest zapisywane.",
        "nl": "Laat %@ toetsaanslagen volgen voor `:`. Er wordt niets vastgelegd.",
        "ar": "يتيح لـ %@ مراقبة الضغطات بحثاً عن `:`. لا يُسجَّل شيء.",
        "fa": "به %@ اجازه می‌دهد ضربه‌های `:` را پی بگیرد. هیچ‌چیز ذخیره نمی‌شود.",
        "he": "מאפשר ל-%@ לעקוב אחר הקשות `:`. דבר לא נשמר.",
    },
    "No ads, tracking, or subscriptions.": {
        "en-GB": "No ads, tracking, or subscriptions.",
        "de": "Keine Werbung, kein Tracking, keine Abos.",
        "es": "Sin anuncios, seguimiento ni suscripciones.",
        "es-419": "Sin anuncios, rastreo ni suscripciones.",
        "fr": "Pas de pubs, pas de pistage, pas d'abonnement.",
        "it": "Niente pubblicità, tracciamento o abbonamenti.",
        "pt-BR": "Sem anúncios, rastreamento ou assinaturas.",
        "ja": "広告、トラッキング、サブスクリプションは一切ありません。",
        "zh-Hans": "无广告、无追踪、无订阅。",
        "zh-Hant": "無廣告、無追蹤、無訂閱。",
        "ko": "광고도, 추적도, 구독도 없습니다.",
        "hi": "कोई विज्ञापन, ट्रैकिंग या सदस्यता नहीं।",
        "ru": "Без рекламы, отслеживания и подписок.",
        "pl": "Bez reklam, śledzenia i subskrypcji.",
        "nl": "Geen advertenties, tracking of abonnementen.",
        "ar": "لا إعلانات، لا تتبّع، لا اشتراكات.",
        "fa": "بدون تبلیغ، ردیابی یا اشتراک.",
        "he": "ללא פרסומות, מעקב או מנויים.",
    },
    "No emoji for :%@:": {
        "en-GB": "No emoji for :%@:",
        "de": "Kein Emoji für :%@:",
        "es": "No hay emoji para :%@:",
        "es-419": "No hay emoji para :%@:",
        "fr": "Aucun émoji pour :%@:",
        "it": "Nessuna emoji per :%@:",
        "pt-BR": "Nenhum emoji para :%@:",
        "ja": ":%@: に対応する絵文字はありません",
        "zh-Hans": "没有 :%@: 对应的 emoji",
        "zh-Hant": "找不到 :%@: 對應的 emoji",
        "ko": ":%@: 에 해당하는 이모지가 없습니다",
        "hi": ":%@: के लिए कोई इमोजी नहीं",
        "ru": "Нет эмодзи для :%@:",
        "pl": "Brak emoji dla :%@:",
        "nl": "Geen emoji voor :%@:",
        "ar": "لا توجد إيموجي لـ :%@:",
        "fa": "ایموجی‌ای برای :%@: یافت نشد",
        "he": "אין אימוג'י עבור :%@:",
    },
    "Open settings": {
        "en-GB": "Open settings",
        "de": "Einstellungen öffnen",
        "es": "Abrir ajustes",
        "es-419": "Abrir ajustes",
        "fr": "Ouvrir les réglages",
        "it": "Apri impostazioni",
        "pt-BR": "Abrir ajustes",
        "ja": "設定を開く",
        "zh-Hans": "打开设置",
        "zh-Hant": "打開設定",
        "ko": "설정 열기",
        "hi": "सेटिंग्स खोलें",
        "ru": "Открыть настройки",
        "pl": "Otwórz ustawienia",
        "nl": "Open instellingen",
        "ar": "فتح الإعدادات",
        "fa": "باز کردن تنظیمات",
        "he": "פתח הגדרות",
    },
    "Open source and auditable": {
        "en-GB": "Open source and auditable",
        "de": "Open Source und überprüfbar",
        "es": "De código abierto y auditable",
        "es-419": "De código abierto y auditable",
        "fr": "Open source et vérifiable",
        "it": "Open source e verificabile",
        "pt-BR": "Código aberto e auditável",
        "ja": "オープンソースで監査可能",
        "zh-Hans": "开源,可审计",
        "zh-Hant": "開源、可審核",
        "ko": "오픈 소스, 직접 확인 가능",
        "hi": "ओपन सोर्स और जाँच-योग्य",
        "ru": "Открытый исходный код, можно проверить",
        "pl": "Open source, można sprawdzić",
        "nl": "Open source en controleerbaar",
        "ar": "مفتوح المصدر وقابل للمراجعة",
        "fa": "متن‌باز و قابل بررسی",
        "he": "קוד פתוח וניתן לביקורת",
    },
    "Pause for 1 hour": {
        "en-GB": "Pause for 1 hour",
        "de": "Eine Stunde pausieren",
        "es": "Pausar 1 hora",
        "es-419": "Pausar 1 hora",
        "fr": "Mettre en pause 1 heure",
        "it": "Pausa per 1 ora",
        "pt-BR": "Pausar por 1 hora",
        "ja": "1時間一時停止",
        "zh-Hans": "暂停 1 小时",
        "zh-Hant": "暫停 1 小時",
        "ko": "1시간 동안 일시 중지",
        "hi": "1 घंटे के लिए रोकें",
        "ru": "Пауза на 1 час",
        "pl": "Wstrzymaj na 1 godzinę",
        "nl": "1 uur pauzeren",
        "ar": "إيقاف مؤقّت لمدّة ساعة",
        "fa": "توقف برای ۱ ساعت",
        "he": "השהה לשעה אחת",
    },
    "Pause until tomorrow": {
        "en-GB": "Pause until tomorrow",
        "de": "Bis morgen pausieren",
        "es": "Pausar hasta mañana",
        "es-419": "Pausar hasta mañana",
        "fr": "Mettre en pause jusqu'à demain",
        "it": "Pausa fino a domani",
        "pt-BR": "Pausar até amanhã",
        "ja": "明日まで一時停止",
        "zh-Hans": "暂停到明天",
        "zh-Hant": "暫停到明天",
        "ko": "내일까지 일시 중지",
        "hi": "कल तक के लिए रोकें",
        "ru": "Пауза до завтра",
        "pl": "Wstrzymaj do jutra",
        "nl": "Pauzeer tot morgen",
        "ar": "إيقاف مؤقّت حتى الغد",
        "fa": "توقف تا فردا",
        "he": "השהה עד מחר",
    },
    "Permissions": {
        "en-GB": "Permissions",
        "de": "Berechtigungen",
        "es": "Permisos",
        "es-419": "Permisos",
        "fr": "Autorisations",
        "it": "Permessi",
        "pt-BR": "Permissões",
        "ja": "権限",
        "zh-Hans": "权限",
        "zh-Hant": "權限",
        "ko": "권한",
        "hi": "अनुमतियाँ",
        "ru": "Разрешения",
        "pl": "Uprawnienia",
        "nl": "Toestemmingen",
        "ar": "الأذونات",
        "fa": "اجازه‌ها",
        "he": "הרשאות",
    },
    "Prevent %@ from triggering inside these apps.": {
        "en-GB": "Prevent %@ from triggering inside these apps.",
        "de": "Verhindere, dass %@ in diesen Apps auslöst.",
        "es": "Evita que %@ se active dentro de estas apps.",
        "es-419": "Evitá que %@ se active dentro de estas apps.",
        "fr": "Empêche %@ de se déclencher dans ces apps.",
        "it": "Impedisci a %@ di attivarsi in queste app.",
        "pt-BR": "Impede que %@ seja acionado dentro destes apps.",
        "ja": "これらのアプリ内で %@ が動作しないようにします。",
        "zh-Hans": "在这些 App 内不触发 %@。",
        "zh-Hant": "在這些 App 內不觸發 %@。",
        "ko": "이 앱들 안에서는 %@이(가) 작동하지 않도록 합니다.",
        "hi": "इन ऐप्स के अंदर %@ को सक्रिय होने से रोकें।",
        "ru": "Не запускать %@ внутри этих приложений.",
        "pl": "Nie uruchamiaj %@ w tych aplikacjach.",
        "nl": "Voorkom dat %@ in deze apps actief is.",
        "ar": "منع تشغيل %@ داخل هذه التطبيقات.",
        "fa": "‏%@ در این برنامه‌ها فعال نشود.",
        "he": "מנע מ-%@ לפעול בתוך אפליקציות אלו.",
    },
    "Prevent %@ from triggering on these sites. `*` matches a subdomain.": {
        "en-GB": "Prevent %@ from triggering on these sites. `*` matches a subdomain.",
        "de": "Verhindere, dass %@ auf diesen Seiten auslöst. `*` steht für eine Subdomain.",
        "es": "Evita que %@ se active en estos sitios. `*` representa un subdominio.",
        "es-419": "Evitá que %@ se active en estos sitios. `*` representa un subdominio.",
        "fr": "Empêche %@ de se déclencher sur ces sites. `*` correspond à un sous-domaine.",
        "it": "Impedisci a %@ di attivarsi su questi siti. `*` rappresenta un sottodominio.",
        "pt-BR": "Impede que %@ seja acionado nestes sites. `*` corresponde a um subdomínio.",
        "ja": "これらのサイトで %@ が動作しないようにします。`*` はサブドメインを表します。",
        "zh-Hans": "在这些网站上不触发 %@。`*` 匹配子域名。",
        "zh-Hant": "在這些網站上不觸發 %@。`*` 匹配子網域。",
        "ko": "이 사이트들에서는 %@이(가) 작동하지 않도록 합니다. `*` 는 하위 도메인을 의미합니다.",
        "hi": "इन साइटों पर %@ को सक्रिय होने से रोकें। `*` एक उपडोमेन से मेल खाता है।",
        "ru": "Не запускать %@ на этих сайтах. `*` соответствует поддомену.",
        "pl": "Nie uruchamiaj %@ na tych witrynach. `*` pasuje do subdomeny.",
        "nl": "Voorkom dat %@ op deze sites actief is. `*` komt overeen met een subdomein.",
        "ar": "منع تشغيل %@ على هذه المواقع. `*` يطابق نطاقاً فرعياً.",
        "fa": "‏%@ در این سایت‌ها فعال نشود. `*` با زیردامنه‌ها مطابقت می‌کند.",
        "he": "מנע מ-%@ לפעול באתרים אלה. `*` מתאים לתת-דומיין.",
    },
    "Press the same shortcut again while paused to resume.": {
        "en-GB": "Press the same shortcut again while paused to resume.",
        "de": "Drücke dieselbe Tastenkombination während der Pause erneut, um fortzufahren.",
        "es": "Pulsa el mismo atajo de nuevo mientras está en pausa para reanudar.",
        "es-419": "Apretá el mismo atajo de nuevo durante la pausa para reanudar.",
        "fr": "Appuyez à nouveau sur le même raccourci pendant la pause pour reprendre.",
        "it": "Premi di nuovo la stessa scorciatoia in pausa per riprendere.",
        "pt-BR": "Pressione o mesmo atalho durante a pausa para retomar.",
        "ja": "一時停止中に同じショートカットをもう一度押すと再開します。",
        "zh-Hans": "暂停期间再次按相同的快捷键即可恢复。",
        "zh-Hant": "暫停期間再次按相同的快捷鍵即可恢復。",
        "ko": "일시 중지 중에 같은 단축키를 다시 누르면 다시 시작됩니다.",
        "hi": "रुके होने पर वही शॉर्टकट दोबारा दबाने से फिर शुरू हो जाएगा।",
        "ru": "Нажмите тот же сочетание клавиш во время паузы, чтобы продолжить.",
        "pl": "Naciśnij ten sam skrót podczas wstrzymania, by wznowić.",
        "nl": "Druk tijdens de pauze opnieuw op dezelfde sneltoets om te hervatten.",
        "ar": "اضغط الاختصار نفسه أثناء الإيقاف المؤقّت للاستئناف.",
        "fa": "در حالت توقف، همان میان‌بر را دوباره فشار دهید تا ادامه یابد.",
        "he": "לחץ שוב על אותו קיצור בעת ההשהיה כדי להמשיך.",
    },
    "Privacy": {
        "en-GB": "Privacy",
        "de": "Datenschutz",
        "es": "Privacidad",
        "es-419": "Privacidad",
        "fr": "Confidentialité",
        "it": "Privacy",
        "pt-BR": "Privacidade",
        "ja": "プライバシー",
        "zh-Hans": "隐私",
        "zh-Hant": "私隱",
        "ko": "개인정보",
        "hi": "निजता",
        "ru": "Конфиденциальность",
        "pl": "Prywatność",
        "nl": "Privacy",
        "ar": "الخصوصية",
        "fa": "حریم خصوصی",
        "he": "פרטיות",
    },
    "Privacy details…": {
        "en-GB": "Privacy details…",
        "de": "Datenschutz-Details…",
        "es": "Detalles de privacidad…",
        "es-419": "Detalles de privacidad…",
        "fr": "Détails de confidentialité…",
        "it": "Dettagli sulla privacy…",
        "pt-BR": "Detalhes de privacidade…",
        "ja": "プライバシーの詳細…",
        "zh-Hans": "隐私详情…",
        "zh-Hant": "私隱詳情…",
        "ko": "개인정보 자세히…",
        "hi": "निजता विवरण…",
        "ru": "Подробнее о конфиденциальности…",
        "pl": "Szczegóły prywatności…",
        "nl": "Privacydetails…",
        "ar": "تفاصيل الخصوصية…",
        "fa": "جزئیات حریم خصوصی…",
        "he": "פרטי פרטיות…",
    },
    "Quit %@": {
        "en-GB": "Quit %@",
        "de": "%@ beenden",
        "es": "Salir de %@",
        "es-419": "Salir de %@",
        "fr": "Quitter %@",
        "it": "Esci da %@",
        "pt-BR": "Encerrar %@",
        "ja": "%@ を終了",
        "zh-Hans": "退出 %@",
        "zh-Hant": "結束 %@",
        "ko": "%@ 종료",
        "hi": "%@ छोड़ें",
        "ru": "Завершить %@",
        "pl": "Zakończ %@",
        "nl": "Stop %@",
        "ar": "إنهاء %@",
        "fa": "خروج از %@",
        "he": "צא מ-%@",
    },
    "Rank frequently used emoji higher": {
        "en-GB": "Rank frequently used emoji higher",
        "de": "Häufig verwendete Emoji höher einstufen",
        "es": "Priorizar los emoji que usas más",
        "es-419": "Priorizar los emojis que más usás",
        "fr": "Mettre en avant les émoji utilisés souvent",
        "it": "Dai priorità alle emoji più usate",
        "pt-BR": "Priorizar emoji usados com frequência",
        "ja": "よく使う絵文字を上位に表示",
        "zh-Hans": "常用 emoji 排序靠前",
        "zh-Hant": "常用 emoji 排序靠前",
        "ko": "자주 쓰는 이모지를 위로",
        "hi": "अक्सर इस्तेमाल किए जाने वाले इमोजी ऊपर रखें",
        "ru": "Часто используемые эмодзи выше",
        "pl": "Pokazuj często używane emoji wyżej",
        "nl": "Veelgebruikte emoji hoger sorteren",
        "ar": "ترتيب الإيموجي الأكثر استخداماً في الأعلى",
        "fa": "ایموجی‌های پرکاربرد بالاتر باشند",
        "he": "דרג גבוה יותר אימוג'י שאתה משתמש בהם הרבה",
    },
    "Report an issue": {
        "en-GB": "Report an issue",
        "de": "Problem melden",
        "es": "Informar de un problema",
        "es-419": "Informar un problema",
        "fr": "Signaler un problème",
        "it": "Segnala un problema",
        "pt-BR": "Relatar um problema",
        "ja": "問題を報告",
        "zh-Hans": "报告问题",
        "zh-Hant": "回報問題",
        "ko": "문제 신고",
        "hi": "समस्या रिपोर्ट करें",
        "ru": "Сообщить о проблеме",
        "pl": "Zgłoś problem",
        "nl": "Meld een probleem",
        "ar": "الإبلاغ عن مشكلة",
        "fa": "گزارش مشکل",
        "he": "דווח על בעיה",
    },
    "Require `::` to search symbols": {
        "en-GB": "Require `::` to search symbols",
        "de": "`::` zum Suchen von Symbolen verlangen",
        "es": "Requerir `::` para buscar símbolos",
        "es-419": "Requerir `::` para buscar símbolos",
        "fr": "Exiger `::` pour rechercher des symboles",
        "it": "Richiedi `::` per cercare simboli",
        "pt-BR": "Exigir `::` para buscar símbolos",
        "ja": "記号の検索に `::` を必須にする",
        "zh-Hans": "搜索符号需要输入 `::`",
        "zh-Hant": "搜尋符號需要輸入 `::`",
        "ko": "기호 검색 시 `::` 입력 필요",
        "hi": "प्रतीक खोजने के लिए `::` अनिवार्य",
        "ru": "Требовать `::` для поиска символов",
        "pl": "Wymagaj `::` do wyszukiwania symboli",
        "nl": "Vereis `::` om symbolen te zoeken",
        "ar": "اشترط `::` للبحث عن الرموز",
        "fa": "برای جست‌وجوی نمادها `::` لازم باشد",
        "he": "דרוש `::` כדי לחפש סמלים",
    },
    "Reset all easter egg progress?": {
        "en-GB": "Reset all easter egg progress?",
        "de": "Allen Easter-Egg-Fortschritt zurücksetzen?",
        "es": "¿Restablecer el progreso de los huevos de pascua?",
        "es-419": "¿Restablecer el progreso de los huevos de pascua?",
        "fr": "Réinitialiser la progression des easter eggs ?",
        "it": "Vuoi azzerare i progressi degli easter egg?",
        "pt-BR": "Redefinir todo o progresso dos easter eggs?",
        "ja": "イースターエッグの進捗をすべてリセットしますか?",
        "zh-Hans": "重置所有彩蛋进度?",
        "zh-Hant": "重設所有彩蛋進度?",
        "ko": "이스터에그 진행 상황을 모두 초기화할까요?",
        "hi": "क्या सभी ईस्टर एग प्रगति रीसेट कर दें?",
        "ru": "Сбросить весь прогресс по пасхалкам?",
        "pl": "Zresetować cały postęp easter eggs?",
        "nl": "Alle easter-egg-voortgang terugzetten?",
        "ar": "هل تريد إعادة تعيين كلّ تقدّم البيوض المفاجِئة؟",
        "fa": "تمام پیشرفت تخم‌مرغ‌های نوروزی پاک شود؟",
        "he": "לאפס את כל ההתקדמות בביצי הפסחא?",
    },
    "Reset eggs": {
        "en-GB": "Reset eggs",
        "de": "Eggs zurücksetzen",
        "es": "Restablecer huevos",
        "es-419": "Restablecer huevos",
        "fr": "Réinitialiser les eggs",
        "it": "Azzera gli egg",
        "pt-BR": "Redefinir eggs",
        "ja": "エッグをリセット",
        "zh-Hans": "重置彩蛋",
        "zh-Hant": "重設彩蛋",
        "ko": "에그 초기화",
        "hi": "एग रीसेट करें",
        "ru": "Сбросить пасхалки",
        "pl": "Zresetuj eggs",
        "nl": "Eggs herstellen",
        "ar": "إعادة تعيين البيوض",
        "fa": "پاک‌کردن تخم‌مرغ‌ها",
        "he": "אפס ביצים",
    },
    "Reset eggs...": {
        "en-GB": "Reset eggs…",
        "de": "Eggs zurücksetzen…",
        "es": "Restablecer huevos…",
        "es-419": "Restablecer huevos…",
        "fr": "Réinitialiser les eggs…",
        "it": "Azzera gli egg…",
        "pt-BR": "Redefinir eggs…",
        "ja": "エッグをリセット…",
        "zh-Hans": "重置彩蛋…",
        "zh-Hant": "重設彩蛋…",
        "ko": "에그 초기화…",
        "hi": "एग रीसेट करें…",
        "ru": "Сбросить пасхалки…",
        "pl": "Zresetuj eggs…",
        "nl": "Eggs herstellen…",
        "ar": "إعادة تعيين البيوض…",
        "fa": "پاک‌کردن تخم‌مرغ‌ها…",
        "he": "אפס ביצים…",
    },
    "Resume": {
        "en-GB": "Resume",
        "de": "Fortsetzen",
        "es": "Reanudar",
        "es-419": "Reanudar",
        "fr": "Reprendre",
        "it": "Riprendi",
        "pt-BR": "Retomar",
        "ja": "再開",
        "zh-Hans": "继续",
        "zh-Hant": "繼續",
        "ko": "다시 시작",
        "hi": "फिर शुरू करें",
        "ru": "Продолжить",
        "pl": "Wznów",
        "nl": "Hervat",
        "ar": "استئناف",
        "fa": "ادامه",
        "he": "המשך",
    },
    "Settings…": {
        "en-GB": "Settings…",
        "de": "Einstellungen…",
        "es": "Ajustes…",
        "es-419": "Ajustes…",
        "fr": "Réglages…",
        "it": "Impostazioni…",
        "pt-BR": "Ajustes…",
        "ja": "設定…",
        "zh-Hans": "设置…",
        "zh-Hant": "設定…",
        "ko": "설정…",
        "hi": "सेटिंग्स…",
        "ru": "Настройки…",
        "pl": "Ustawienia…",
        "nl": "Instellingen…",
        "ar": "الإعدادات…",
        "fa": "تنظیمات…",
        "he": "הגדרות…",
    },
    "Show Onboarding": {
        "en-GB": "Show Onboarding",
        "de": "Einführung anzeigen",
        "es": "Mostrar la bienvenida",
        "es-419": "Mostrar la bienvenida",
        "fr": "Afficher l'onboarding",
        "it": "Mostra l'onboarding",
        "pt-BR": "Mostrar onboarding",
        "ja": "オンボーディングを表示",
        "zh-Hans": "显示引导",
        "zh-Hant": "顯示引導",
        "ko": "온보딩 보기",
        "hi": "ऑनबोर्डिंग दिखाएँ",
        "ru": "Показать вступительный обзор",
        "pl": "Pokaż wprowadzenie",
        "nl": "Toon onboarding",
        "ar": "عرض الإعداد الترحيبي",
        "fa": "نمایش راه‌اندازی اولیه",
        "he": "הצג מסך הצטרפות",
    },
    "Show icon in menu bar": {
        "en-GB": "Show icon in menu bar",
        "de": "Symbol in der Menüleiste anzeigen",
        "es": "Mostrar icono en la barra de menús",
        "es-419": "Mostrar ícono en la barra de menús",
        "fr": "Afficher l'icône dans la barre de menus",
        "it": "Mostra l'icona nella barra dei menu",
        "pt-BR": "Mostrar ícone na barra de menus",
        "ja": "メニューバーにアイコンを表示",
        "zh-Hans": "在菜单栏中显示图标",
        "zh-Hant": "在選單列中顯示圖示",
        "ko": "메뉴 막대에 아이콘 표시",
        "hi": "मेन्यू बार में आइकन दिखाएँ",
        "ru": "Показывать значок в строке меню",
        "pl": "Pokaż ikonę na pasku menu",
        "nl": "Toon pictogram in menubalk",
        "ar": "إظهار الأيقونة في شريط القوائم",
        "fa": "نمایش آیکون در نوار منو",
        "he": "הצג צלמית בשורת התפריטים",
    },
    "Skin tone": {
        "en-GB": "Skin tone",
        "de": "Hautton",
        "es": "Tono de piel",
        "es-419": "Tono de piel",
        "fr": "Teinte de peau",
        "it": "Tono della pelle",
        "pt-BR": "Tom de pele",
        "ja": "肌の色",
        "zh-Hans": "肤色",
        "zh-Hant": "膚色",
        "ko": "피부색",
        "hi": "त्वचा का रंग",
        "ru": "Тон кожи",
        "pl": "Odcień skóry",
        "nl": "Huidtint",
        "ar": "لون البشرة",
        "fa": "رنگ پوست",
        "he": "גוון עור",
    },
    "Start at login": {
        "en-GB": "Start at login",
        "de": "Beim Anmelden starten",
        "es": "Iniciar al iniciar sesión",
        "es-419": "Iniciar al iniciar sesión",
        "fr": "Lancer à l'ouverture de session",
        "it": "Avvia all'accesso",
        "pt-BR": "Iniciar ao fazer login",
        "ja": "ログイン時に起動",
        "zh-Hans": "登录时启动",
        "zh-Hant": "登入時啟動",
        "ko": "로그인 시 시작",
        "hi": "लॉगिन पर शुरू करें",
        "ru": "Запускать при входе",
        "pl": "Uruchamiaj przy logowaniu",
        "nl": "Start bij inloggen",
        "ar": "البدء عند تسجيل الدخول",
        "fa": "اجرا هنگام ورود",
        "he": "הפעל בעת הכניסה",
    },
    "Thank you": {
        # Spoken aloud (AVSpeechSynthesizer) when "I donated" is toggled
        # on in About. Keep short — a word/phrase, not a sentence.
        "en-GB": "Thank you",
        "de": "Danke",
        "es": "Gracias",
        "es-419": "Gracias",
        "fr": "Merci",
        "it": "Grazie",
        "pt-BR": "Obrigado",
        "ja": "ありがとう",
        "zh-Hans": "谢谢",
        "zh-Hant": "謝謝",
        "ko": "감사합니다",
        "hi": "धन्यवाद",
        "ru": "Спасибо",
        "pl": "Dziękuję",
        "nl": "Bedankt",
        "ar": "شكراً",
        "fa": "ممنون",
        "he": "תודה",
    },
    "Stats": {
        "en-GB": "Stats",
        "de": "Statistiken",
        "es": "Estadísticas",
        "es-419": "Estadísticas",
        "fr": "Statistiques",
        "it": "Statistiche",
        "pt-BR": "Estatísticas",
        "ja": "統計",
        "zh-Hans": "统计",
        "zh-Hant": "統計",
        "ko": "통계",
        "hi": "आँकड़े",
        "ru": "Статистика",
        "pl": "Statystyki",
        "nl": "Statistieken",
        "ar": "الإحصاءات",
        "fa": "آمار",
        "he": "סטטיסטיקות",
    },
    "Support Wells": {
        # "Wells" is a proper name (the developer). Keep verbatim.
        "en-GB": "Support Wells",
        "de": "Wells unterstützen",
        "es": "Apoya a Wells",
        "es-419": "Apoyá a Wells",
        "fr": "Soutenir Wells",
        "it": "Sostieni Wells",
        "pt-BR": "Apoiar Wells",
        "ja": "Wells を支援する",
        "zh-Hans": "支持 Wells",
        "zh-Hant": "支持 Wells",
        "ko": "Wells 후원하기",
        "hi": "Wells का सहयोग करें",
        "ru": "Поддержать Wells",
        "pl": "Wesprzyj Wellsa",
        "nl": "Steun Wells",
        "ar": "ادعم Wells",
        "fa": "از Wells حمایت کنید",
        "he": "תמוך ב-Wells",
    },
    "This will erase your autocomplete stats and Top 8. Settings and exclusions won't be changed.": {
        "en-GB": "This will erase your autocomplete stats and Top 8. Settings and exclusions won't be changed.",
        "de": "Damit werden deine Autovervollständigungs-Statistiken und Top 8 gelöscht. Einstellungen und Ausnahmen bleiben unverändert.",
        "es": "Esto borrará tus estadísticas de autocompletado y tu Top 8. Los ajustes y exclusiones no cambiarán.",
        "es-419": "Esto borrará tus estadísticas de autocompletado y tu Top 8. Los ajustes y exclusiones no cambiarán.",
        "fr": "Cela effacera vos statistiques d'autocomplétion et votre Top 8. Les réglages et exclusions ne changeront pas.",
        "it": "Verranno cancellate le statistiche di completamento automatico e la Top 8. Impostazioni ed esclusioni resteranno invariate.",
        "pt-BR": "Isso apagará suas estatísticas de autocompletar e o Top 8. Os ajustes e exclusões não serão alterados.",
        "ja": "自動補完の統計と Top 8 を削除します。設定と除外リストは変更されません。",
        "zh-Hans": "此操作将清除你的自动补全统计和 Top 8。设置和排除项不会改变。",
        "zh-Hant": "此操作將清除你的自動完成統計和 Top 8。設定和排除項目不會改變。",
        "ko": "자동 완성 통계와 Top 8이(가) 삭제됩니다. 설정과 제외 항목은 변경되지 않습니다.",
        "hi": "इससे आपके ऑटोकम्प्लीट आँकड़े और टॉप 8 हट जाएँगे। सेटिंग्स और अपवर्जन नहीं बदलेंगे।",
        "ru": "Это удалит вашу статистику автодополнения и Top 8. Настройки и исключения не изменятся.",
        "pl": "Wyczyści to twoje statystyki autouzupełniania i Top 8. Ustawienia i wykluczenia pozostaną bez zmian.",
        "nl": "Hiermee verwijder je je autocomplete-statistieken en Top 8. Instellingen en uitsluitingen blijven onveranderd.",
        "ar": "سيؤدّي ذلك إلى مسح إحصاءات الإكمال التلقائي وقائمة الـ Top 8 الخاصة بك. لن تتغيّر الإعدادات والاستثناءات.",
        "fa": "این کار آمار تکمیل خودکار و Top 8 شما را پاک می‌کند. تنظیمات و موارد مستثنا تغییری نمی‌کنند.",
        "he": "פעולה זו תמחק את סטטיסטיקות ההשלמה האוטומטית ואת ה-Top 8 שלך. ההגדרות וההחרגות יישארו כפי שהן.",
    },
    "This will erase your discovery progress and any per-egg counters. The eggs themselves still work — you'll just need to find them again.": {
        "en-GB": "This will erase your discovery progress and any per-egg counters. The eggs themselves still work — you'll just need to find them again.",
        "de": "Damit werden dein Entdeckungs-Fortschritt und alle eggs-spezifischen Zähler gelöscht. Die Eggs selbst funktionieren weiter – du musst sie nur wieder finden.",
        "es": "Esto borrará tu progreso de descubrimiento y los contadores de cada egg. Los eggs siguen funcionando — solo tendrás que encontrarlos otra vez.",
        "es-419": "Esto borrará tu progreso de descubrimiento y los contadores de cada egg. Los eggs siguen funcionando — solo tendrás que encontrarlos otra vez.",
        "fr": "Cela effacera votre progression et les compteurs propres à chaque egg. Les eggs continuent de fonctionner — il faudra juste les retrouver.",
        "it": "Verranno cancellati i tuoi progressi e tutti i contatori dei singoli egg. Gli egg continuano a funzionare — dovrai solo ritrovarli.",
        "pt-BR": "Isso apagará seu progresso de descoberta e os contadores de cada egg. Os eggs continuam funcionando — você só precisará encontrá-los de novo.",
        "ja": "発見の進捗と各エッグごとのカウンターを削除します。エッグ自体は動作するので、また見つけ直してください。",
        "zh-Hans": "此操作将清除你的发现进度和每个彩蛋的计数。彩蛋本身仍然有效 — 你只需重新发现它们。",
        "zh-Hant": "此操作將清除你的發現進度和每個彩蛋的計數。彩蛋本身仍然有效 — 你只需重新發現它們。",
        "ko": "발견 진행 상황과 에그별 카운터가 삭제됩니다. 에그 자체는 그대로 동작하니, 다시 찾으면 됩니다.",
        "hi": "इससे आपकी खोज प्रगति और हर एग के काउंटर मिट जाएँगे। एग खुद काम करते रहेंगे — आपको बस उन्हें फिर से ढूँढना होगा।",
        "ru": "Это удалит ваш прогресс открытий и все счётчики по конкретным пасхалкам. Сами пасхалки продолжат работать — просто найдёте их заново.",
        "pl": "Wyczyści to twój postęp odkrywania i liczniki poszczególnych easter eggs. Same eggs nadal działają — wystarczy je odkryć ponownie.",
        "nl": "Hiermee verwijder je je ontdekkings­voortgang en alle per-egg-tellers. De eggs zelf werken nog steeds — je hoeft ze gewoon opnieuw te vinden.",
        "ar": "سيؤدّي ذلك إلى مسح تقدّم اكتشافك وكل عدّادات البيوض الفردية. البيوض نفسها ستظلّ تعمل — ستحتاج فقط للعثور عليها من جديد.",
        "fa": "این کار پیشرفت کشف و شمارنده‌های هر تخم‌مرغ را پاک می‌کند. خود تخم‌مرغ‌ها همچنان کار می‌کنند — فقط باید دوباره پیدای‌شان کنید.",
        "he": "פעולה זו תמחק את התקדמות הגילוי ואת המונים של כל ביצה. הביצים עצמן ימשיכו לעבוד — פשוט תצטרך למצוא אותן שוב.",
    },
    "Type `:` to search for any emoji or symbol in seconds.": {
        "en-GB": "Type `:` to search for any emoji or symbol in seconds.",
        "de": "Tippe `:`, um in Sekunden ein Emoji oder Symbol zu finden.",
        "es": "Escribe `:` para buscar cualquier emoji o símbolo en segundos.",
        "es-419": "Escribí `:` para buscar cualquier emoji o símbolo en segundos.",
        "fr": "Tapez `:` pour trouver n'importe quel émoji ou symbole en quelques secondes.",
        "it": "Digita `:` per cercare qualsiasi emoji o simbolo in pochi secondi.",
        "pt-BR": "Digite `:` para buscar qualquer emoji ou símbolo em segundos.",
        "ja": "`:` を入力すれば、絵文字や記号を数秒で検索できます。",
        "zh-Hans": "输入 `:` 即可在数秒内搜索任意 emoji 或符号。",
        "zh-Hant": "輸入 `:` 即可在數秒內搜尋任意 emoji 或符號。",
        "ko": "`:` 만 입력하면 몇 초 만에 이모지나 기호를 찾을 수 있습니다.",
        "hi": "किसी भी इमोजी या प्रतीक को सेकंडों में खोजने के लिए `:` टाइप करें।",
        "ru": "Введите `:`, чтобы за секунды найти любое эмодзи или символ.",
        "pl": "Wpisz `:`, by w sekundę znaleźć dowolne emoji lub symbol.",
        "nl": "Typ `:` om in seconden elke emoji of symbool te zoeken.",
        "ar": "اكتب `:` للبحث عن أيّ إيموجي أو رمز في ثوانٍ.",
        "fa": "برای جست‌وجوی هر ایموجی یا نماد در چند ثانیه، `:` را تایپ کنید.",
        "he": "הקלד `:` כדי לחפש כל אימוג'י או סמל בשניות.",
    },
    "Type some emoji and they'll show up here.": {
        "en-GB": "Type some emoji and they'll show up here.",
        "de": "Tippe ein paar Emoji – sie tauchen dann hier auf.",
        "es": "Escribe algunos emoji y aparecerán aquí.",
        "es-419": "Escribí algunos emojis y aparecerán acá.",
        "fr": "Tapez quelques émoji et ils apparaîtront ici.",
        "it": "Digita qualche emoji e compariranno qui.",
        "pt-BR": "Digite alguns emoji e eles aparecerão aqui.",
        "ja": "絵文字をいくつか入力すると、ここに表示されます。",
        "zh-Hans": "输入一些 emoji,它们就会显示在这里。",
        "zh-Hant": "輸入一些 emoji,它們就會顯示在這裡。",
        "ko": "이모지를 몇 개 입력하면 여기에 나타납니다.",
        "hi": "कुछ इमोजी टाइप करें, वे यहाँ दिखेंगे।",
        "ru": "Введите несколько эмодзи — они появятся здесь.",
        "pl": "Wpisz kilka emoji, a pojawią się tutaj.",
        "nl": "Typ wat emoji en ze verschijnen hier.",
        "ar": "اكتب بعض الإيموجي وستظهر هنا.",
        "fa": "چند ایموجی تایپ کنید تا اینجا نمایش داده شوند.",
        "he": "הקלד כמה אימוג'י והם יופיעו כאן.",
    },
    "Update check failed": {
        "en-GB": "Update check failed",
        "de": "Update-Prüfung fehlgeschlagen",
        "es": "Error al buscar actualizaciones",
        "es-419": "Falló la búsqueda de actualizaciones",
        "fr": "Échec de la vérification des mises à jour",
        "it": "Verifica aggiornamenti non riuscita",
        "pt-BR": "Falha ao verificar atualizações",
        "ja": "アップデートの確認に失敗しました",
        "zh-Hans": "检查更新失败",
        "zh-Hant": "檢查更新失敗",
        "ko": "업데이트 확인 실패",
        "hi": "अपडेट जाँच विफल",
        "ru": "Не удалось проверить обновления",
        "pl": "Sprawdzanie aktualizacji nieudane",
        "nl": "Update controleren mislukt",
        "ar": "فشل التحقّق من التحديثات",
        "fa": "بررسی به‌روزرسانی شکست خورد",
        "he": "בדיקת העדכון נכשלה",
    },
    "Usage counts, settings, and your exclusion list are stored locally. %@ doesn't send any telemetry or usage data back to our server—we don't even have a server 🙂": {
        "en-GB": "Usage counts, settings, and your exclusion list are stored locally. %@ doesn't send any telemetry or usage data back to our server—we don't even have a server 🙂",
        "de": "Nutzungszähler, Einstellungen und deine Ausnahmeliste werden lokal gespeichert. %@ sendet keine Telemetrie- oder Nutzungsdaten an einen Server – wir haben nicht mal einen 🙂",
        "es": "Los contadores de uso, los ajustes y tu lista de exclusiones se guardan localmente. %@ no envía telemetría ni datos de uso a un servidor — ni siquiera tenemos servidor 🙂",
        "es-419": "Los contadores de uso, los ajustes y tu lista de exclusiones se guardan localmente. %@ no envía telemetría ni datos de uso a un servidor — ni siquiera tenemos servidor 🙂",
        "fr": "Les compteurs d'utilisation, les réglages et votre liste d'exclusions restent en local. %@ n'envoie aucune télémétrie ni donnée d'usage à un serveur — on n'a même pas de serveur 🙂",
        "it": "I contatori d'uso, le impostazioni e l'elenco delle esclusioni restano in locale. %@ non invia telemetria o dati di utilizzo a un server — non abbiamo nemmeno un server 🙂",
        "pt-BR": "Os contadores de uso, os ajustes e sua lista de exclusões ficam no seu Mac. %@ não envia telemetria nem dados de uso para um servidor — a gente nem tem servidor 🙂",
        "ja": "使用回数、設定、除外リストはローカルに保存されます。%@ はテレメトリや利用データをサーバーに送信しません — そもそもサーバーがありません 🙂",
        "zh-Hans": "使用次数、设置和你的排除列表都存在本地。%@ 不会将任何遥测或使用数据发送到服务器 — 我们连服务器都没有 🙂",
        "zh-Hant": "使用次數、設定和你的排除清單都存在本機。%@ 不會將任何遙測或使用資料傳送到伺服器 — 我們根本沒有伺服器 🙂",
        "ko": "사용 횟수, 설정, 제외 목록은 모두 로컬에 저장됩니다. %@은(는) 어떤 텔레메트리나 사용 데이터도 서버로 보내지 않습니다 — 서버 자체가 없어요 🙂",
        "hi": "उपयोग गिनती, सेटिंग्स और आपकी अपवर्जन सूची स्थानीय रूप से सेव होती है। %@ कोई टेलीमेट्री या उपयोग डेटा सर्वर पर नहीं भेजता — हमारे पास सर्वर ही नहीं है 🙂",
        "ru": "Счётчики использования, настройки и список исключений хранятся локально. %@ не отправляет телеметрию и данные использования — у нас даже сервера нет 🙂",
        "pl": "Liczniki użycia, ustawienia i lista wykluczeń są zapisywane lokalnie. %@ nie wysyła żadnej telemetrii ani danych użycia — nie mamy nawet serwera 🙂",
        "nl": "Gebruiksstatistieken, instellingen en je uitsluitingslijst worden lokaal opgeslagen. %@ stuurt geen telemetrie of gebruiksgegevens naar een server — we hebben niet eens een server 🙂",
        "ar": "تُحفظ أعداد الاستخدام والإعدادات وقائمة الاستثناء محلياً. لا يُرسل %@ أيّ بيانات قياس أو استخدام إلى خادم — لا يوجد لدينا خادم أصلاً 🙂",
        "fa": "شمارنده‌های استفاده، تنظیمات و فهرست مستثنیات شما به‌صورت محلی ذخیره می‌شوند. %@ هیچ داده‌ای را به سرور ارسال نمی‌کند — اصلاً ما سروری نداریم 🙂",
        "he": "ספירת השימוש, ההגדרות ורשימת ההחרגות נשמרות מקומית. %@ לא שולח שום נתוני טלמטריה או שימוש לשרת — אין לנו אפילו שרת 🙂",
    },
    "Used to detect `:` triggers. Nothing else.": {
        "en-GB": "Used to detect `:` triggers. Nothing else.",
        "de": "Wird nur zum Erkennen von `:`-Triggern verwendet. Mehr nicht.",
        "es": "Se usa para detectar el `:`. Nada más.",
        "es-419": "Se usa para detectar el `:`. Nada más.",
        "fr": "Sert à détecter les déclencheurs `:`. Rien d'autre.",
        "it": "Serve solo a rilevare il `:`. Nient'altro.",
        "pt-BR": "Usado para detectar o `:`. Nada mais.",
        "ja": "`:` の検出にのみ使用します。それ以外には使いません。",
        "zh-Hans": "仅用于检测 `:` 触发键,无其他用途。",
        "zh-Hant": "僅用於偵測 `:` 觸發鍵,無其他用途。",
        "ko": "`:` 입력 감지에만 사용합니다. 그 외에는 쓰이지 않습니다.",
        "hi": "केवल `:` ट्रिगर्स पहचानने के लिए। और कुछ नहीं।",
        "ru": "Используется только для обнаружения `:`. И больше ничего.",
        "pl": "Służy do wykrywania `:`. Nic więcej.",
        "nl": "Wordt alleen gebruikt om `:` te detecteren. Verder niets.",
        "ar": "يُستخدم فقط لاكتشاف اختصارات `:`. لا شيء غير ذلك.",
        "fa": "فقط برای تشخیص `:` استفاده می‌شود. هیچ‌چیز دیگر.",
        "he": "משמש לזיהוי `:`. שום דבר נוסף.",
    },
    "User since": {
        "en-GB": "User since",
        "de": "Nutzer seit",
        "es": "Usuario desde",
        "es-419": "Usuario desde",
        "fr": "Utilisateur depuis",
        "it": "Utente dal",
        "pt-BR": "Usuário desde",
        "ja": "利用開始",
        "zh-Hans": "用户起始",
        "zh-Hant": "用戶起始",
        "ko": "사용 시작일",
        "hi": "उपयोगकर्ता बने",
        "ru": "Пользователь с",
        "pl": "Użytkownik od",
        "nl": "Gebruiker sinds",
        "ar": "مستخدم منذ",
        "fa": "کاربر از",
        "he": "משתמש מאז",
    },
    "Version %@ (%@)": {
        "en-GB": "Version %1$@ (%2$@)",
        "de": "Version %1$@ (%2$@)",
        "es": "Versión %1$@ (%2$@)",
        "es-419": "Versión %1$@ (%2$@)",
        "fr": "Version %1$@ (%2$@)",
        "it": "Versione %1$@ (%2$@)",
        "pt-BR": "Versão %1$@ (%2$@)",
        "ja": "バージョン %1$@ (%2$@)",
        "zh-Hans": "版本 %1$@ (%2$@)",
        "zh-Hant": "版本 %1$@ (%2$@)",
        "ko": "버전 %1$@ (%2$@)",
        "hi": "संस्करण %1$@ (%2$@)",
        "ru": "Версия %1$@ (%2$@)",
        "pl": "Wersja %1$@ (%2$@)",
        "nl": "Versie %1$@ (%2$@)",
        "ar": "الإصدار %1$@ (%2$@)",
        "fa": "نسخهٔ %1$@ (%2$@)",
        "he": "גרסה %1$@ (%2$@)",
    },
    "View source": {
        "en-GB": "View source",
        "de": "Quellcode ansehen",
        "es": "Ver el código",
        "es-419": "Ver el código",
        "fr": "Voir le code source",
        "it": "Vedi il codice",
        "pt-BR": "Ver o código",
        "ja": "ソースを見る",
        "zh-Hans": "查看源代码",
        "zh-Hant": "檢視原始碼",
        "ko": "소스 보기",
        "hi": "स्रोत देखें",
        "ru": "Открыть исходники",
        "pl": "Zobacz kod",
        "nl": "Bekijk broncode",
        "ar": "عرض المصدر",
        "fa": "مشاهدهٔ کد",
        "he": "צפה בקוד",
    },
    "Watches keystrokes for the `:` trigger.": {
        "en-GB": "Watches keystrokes for the `:` trigger.",
        "de": "Beobachtet Tastenanschläge auf den `:`-Trigger.",
        "es": "Vigila las pulsaciones en busca del `:`.",
        "es-419": "Vigila las pulsaciones en busca del `:`.",
        "fr": "Surveille les frappes pour détecter le déclencheur `:`.",
        "it": "Osserva le digitazioni in cerca del `:`.",
        "pt-BR": "Observa as teclas em busca do `:`.",
        "ja": "`:` のキー入力を監視します。",
        "zh-Hans": "监听 `:` 触发键。",
        "zh-Hant": "監聽 `:` 觸發鍵。",
        "ko": "`:` 입력을 감지합니다.",
        "hi": "`:` ट्रिगर के लिए कीस्ट्रोक देखता है।",
        "ru": "Отслеживает нажатия `:`.",
        "pl": "Obserwuje naciśnięcia `:`.",
        "nl": "Volgt toetsaanslagen voor `:`.",
        "ar": "يراقب الضغطات بحثاً عن `:`.",
        "fa": "ضربه‌های `:` را پی می‌گیرد.",
        "he": "עוקב אחר הקשות `:`.",
    },
    "Website": {
        "en-GB": "Website",
        "de": "Website",
        "es": "Sitio web",
        "es-419": "Sitio web",
        "fr": "Site web",
        "it": "Sito web",
        "pt-BR": "Site",
        "ja": "ウェブサイト",
        "zh-Hans": "网站",
        "zh-Hant": "網站",
        "ko": "웹사이트",
        "hi": "वेबसाइट",
        "ru": "Сайт",
        "pl": "Witryna",
        "nl": "Website",
        "ar": "الموقع الإلكتروني",
        "fa": "وب‌سایت",
        "he": "אתר",
    },
    "You're all set": {
        "en-GB": "You're all set",
        "de": "Alles bereit",
        "es": "Todo listo",
        "es-419": "Todo listo",
        "fr": "Tout est prêt",
        "it": "Tutto pronto",
        "pt-BR": "Tudo pronto",
        "ja": "準備完了です",
        "zh-Hans": "一切就绪",
        "zh-Hant": "一切就緒",
        "ko": "모든 준비가 끝났어요",
        "hi": "सब तैयार है",
        "ru": "Готово к работе",
        "pl": "Wszystko gotowe",
        "nl": "Alles staat klaar",
        "ar": "كلّ شيء جاهز",
        "fa": "همه‌چیز آماده است",
        "he": "הכל מוכן",
    },
    "Your data stays on this Mac": {
        "en-GB": "Your data stays on this Mac",
        "de": "Deine Daten bleiben auf diesem Mac",
        "es": "Tus datos se quedan en este Mac",
        "es-419": "Tus datos se quedan en esta Mac",
        "fr": "Vos données restent sur ce Mac",
        "it": "I tuoi dati restano su questo Mac",
        "pt-BR": "Seus dados ficam neste Mac",
        "ja": "データはこの Mac から出ません",
        "zh-Hans": "你的数据只留在这台 Mac 上",
        "zh-Hant": "你的資料只留在這台 Mac 上",
        "ko": "데이터는 이 Mac에만 머무릅니다",
        "hi": "आपका डेटा इसी Mac पर रहता है",
        "ru": "Ваши данные остаются на этом Mac",
        "pl": "Twoje dane zostają na tym Macu",
        "nl": "Je gegevens blijven op deze Mac",
        "ar": "تبقى بياناتك على هذا الـ Mac",
        "fa": "داده‌های شما روی همین Mac می‌ماند",
        "he": "הנתונים שלך נשארים על ה-Mac הזה",
    },
    "Your top 8": {
        "en-GB": "Your top 8",
        "de": "Deine Top 8",
        "es": "Tu Top 8",
        "es-419": "Tu Top 8",
        "fr": "Votre Top 8",
        "it": "La tua Top 8",
        "pt-BR": "Seu Top 8",
        "ja": "あなたのトップ 8",
        "zh-Hans": "你的 Top 8",
        "zh-Hant": "你的 Top 8",
        "ko": "내 Top 8",
        "hi": "आपका टॉप 8",
        "ru": "Твой Топ 8",
        "pl": "Twój Top 8",
        "nl": "Jouw Top 8",
        "ar": "أفضل 8 لديك",
        "fa": "هشت برتر شما",
        "he": "ה-Top 8 שלך",
    },
    "e.g. mail.google.com or *.notion.so": {
        "en-GB": "e.g. mail.google.com or *.notion.so",
        "de": "z. B. mail.google.com oder *.notion.so",
        "es": "p. ej. mail.google.com o *.notion.so",
        "es-419": "p. ej. mail.google.com o *.notion.so",
        "fr": "p. ex. mail.google.com ou *.notion.so",
        "it": "es. mail.google.com o *.notion.so",
        "pt-BR": "ex.: mail.google.com ou *.notion.so",
        "ja": "例: mail.google.com または *.notion.so",
        "zh-Hans": "例如 mail.google.com 或 *.notion.so",
        "zh-Hant": "例如 mail.google.com 或 *.notion.so",
        "ko": "예: mail.google.com 또는 *.notion.so",
        "hi": "उदा. mail.google.com या *.notion.so",
        "ru": "напр. mail.google.com или *.notion.so",
        "pl": "np. mail.google.com lub *.notion.so",
        "nl": "bijv. mail.google.com of *.notion.so",
        "ar": "مثلاً: mail.google.com أو *.notion.so",
        "fa": "مثلاً mail.google.com یا *.notion.so",
        "he": "למשל mail.google.com או *.notion.so",
    },
}


def main() -> None:
    if not CATALOG.exists():
        sys.exit(f"missing catalog: {CATALOG}")

    catalog = json.loads(CATALOG.read_text())
    strings = catalog.setdefault("strings", {})

    applied = 0
    skipped = 0
    unknown_keys = []

    for key, translations in TRANSLATIONS.items():
        if key not in strings:
            unknown_keys.append(key)
            continue

        entry = strings[key]
        localizations = entry.setdefault("localizations", {})

        for locale in LOCALES:
            value = translations.get(locale)
            if value is None:
                continue

            existing = localizations.get(locale, {}).get("stringUnit", {})
            existing_state = existing.get("state", "new")

            # Preserve manual edits — only overwrite "new" / missing entries.
            if existing_state in ("translated", "needs_review", "reviewed", "stale") \
                    and existing.get("value") not in (None, ""):
                if existing.get("value") == value:
                    continue
                if existing_state != "new":
                    skipped += 1
                    continue

            localizations[locale] = {
                "stringUnit": {"state": "translated", "value": value},
            }
            applied += 1

    if unknown_keys:
        print("warning: keys present in TRANSLATIONS but missing from catalog:")
        for k in unknown_keys:
            print(f"  - {k!r}")

    CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n")
    print(f"Applied {applied} translation(s); skipped {skipped} manual edit(s).")


if __name__ == "__main__":
    main()
